### ISSUE TITLE
[BUG] Null values in indexed fields cause NSCocoaErrorDomain Code=3840

### ISSUE THREAD

**Issue by zaitsman** [forcedotcom/SalesforceMobileSDK-iOS#2775] opened 2019-02-11 06:57 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 7.0.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 12.1
4. Device: iOS iPhone X/Simulator iPhone XS
5. Steps to reproduce: Setup the user store with a json, including a nullable field as index, e.g.
```
{ "path": "MyField__c", "type": "string"},
```
Use SmartSync to fetch some records where this value is `null`
Attempt to get data out of smart store using sosql e.g. `Select {SoupName:MyField__c} FROM {SoupName}`
6. Actual behavior:
```
[SFSDK] CLASS: SFJsonUtils WARNING error parsing json: Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 22." UserInfo={NSDebugDescription=Invalid value around character 22.}
```
7. Expected Behavior:
As per documentation (https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/offline_soup.htm):
```
Index entries that are missing any fields described in an indexSpecs array are not tracked in that index.
```
8. Error Log:
```
[SFSDK] CLASS: SFJsonUtils WARNING error parsing json: Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 22." UserInfo={NSDebugDescription=Invalid value around character 22.}
```

**Comment by zaitsman** [comment] 2019-02-11 07:06
Also the mobile_sdk.pdf (https://resources.docs.salesforce.com/sfdc/pdf/mobile_sdk.pdf) says on page 211: `Index columns can contain null fields.`

**Comment by zaitsman** [comment] 2019-02-11 07:09
And i get this error in the SmartStore inspector:
![image](https://user-images.githubusercontent.com/4538973/52549593-0c36d380-2e28-11e9-83de-bf447ff6fb73.png)

```
2019-02-11 18:07:58.169767+1100 SalesSyncN[28461:6441091] [SFSDK] CLASS: SFJsonUtils WARNING error parsing json: Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 542." UserInfo={NSDebugDescription=Invalid value around character 542.}
```

**Comment by zaitsman** [comment] 2019-02-11 07:13
I just learned that in my code if use sosql i can use `COALESCE` to work around it, e.g.

```
SELECT COALESCE({SoupName:MyField__c}, '') FROM {SoupName}
```
However, in SmartStore inspector the above fails:
![image](https://user-images.githubusercontent.com/4538973/52549721-b282d900-2e28-11e9-9547-64af11a2d676.png)

**Comment by wmathurin** [comment] 2019-02-11 15:02
Dupe of https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2770
Fixed in dev https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2771

**Closed by wmathurin** 2019-02-11 15:02 UTC

**Comment by zaitsman** [comment] 2019-02-11 21:49
@wmathurin thanks for that! Any ETA on this shipping as a release?

**Comment by wmathurin** [comment] 2019-02-14 18:45
Maybe #safeharbor early April - In the meantime, you could cherry pick the fix.
