### ISSUE TITLE
CSFActions with different baseURLs are marked as duplicate.

### ISSUE THREAD

**Issue by amisha10** [forcedotcom/SalesforceMobileSDK-iOS#1763] opened 2016-10-03 17:08 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 4.3.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version:  iOS 10
4. Device: iPhone 6 Plus / Simulator
5. Steps to reproduce: Subclass the CSFAction class and create 2 actions with different base urls but the same method and verb.  Execute the actions.
6. Actual behavior: Both actions get the same response. If the first action returns an error, the second one shows the same error in the completion block. In this specific case , We were trying to create 2 independent live agent sessions to different endpoints. But both the action responses returned the same sessionId and key.
7. Expected Behavior: Actions with different base urls should be fired independently and not considered as duplicates.
8. Error Log: No error log was generated.

**Comment by huminzhi** [comment] 2016-10-04 18:36
The issue is fixed or solved in latest build.
Please try to reproduce again and see if it still exists. Thank you!

**Comment by huminzhi** [comment] 2016-10-04 19:23
The issue is fixed or solved in latest build.
Please try to reproduce again and see if it still exists. Thank you!

**Comment by trooper2013** [comment] 2016-10-04 20:39
@amisha10 The issue  stems from a bug in the implementation of isEqual in CSFAction. If you are unable to update, I would suggest overriding the isEqual implementation for your Action classes with something similar to the following.  
```
- (BOOL)isEqual:(id)object { 

    if (self == object) {
        return YES;
     } 
    BOOL isEqual = [self.baseURL isEqual:action.baseURL];
    isEqual = isEqual && [super isEqual:object] ;
    ....
    return isEqual;

}
```
Let us know if this works for you.

**Comment by amisha10** [comment] 2016-10-04 20:44
@trooper2013 : I have it over ridden in my implementation. I just wanted to make sure it fixed in the subsequent release. 
Thank you for the suggestion.

**Comment by trooper2013** [comment] 2016-10-04 20:46
Thats great. The bug has been fixed in the SDK.

**Comment by amisha10** [comment] 2016-10-04 20:49
Perfect!

**Comment by huminzhi** [comment] 2016-10-05 18:36
The issue is fixed or solved in latest build.
Please try to reproduce again and see if it still exists. Thank you!

**Comment by huminzhi** [comment] 2016-10-06 18:36
The issue is fixed or solved in latest build.
Please try to reproduce again and see if it still exists. Thank you!

**Closed** 2016-10-06 18:58 UTC
Labels: bug
