### ISSUE TITLE
'Use Custom Domain' screen crash when invalid domain entered

### ISSUE THREAD

**Issue by rilchyshyn** [forcedotcom/SalesforceMobileSDK-iOS#2853] opened 2019-05-07 14:28 UTC
We are receiving the same crash report from various clients (see [crashlytics-report.txt](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/3153027/crashlytics-report.txt)).

To reproduce it, just try to enter _wrong_ custom domain value (in 'Use Custom Domain' screen) **twice** (see [how-to-reproduce](https://user-images.githubusercontent.com/48205812/57307210-d2a2fb00-70ec-11e9-830b-b1672a1500e4.gif)).

The issue caused on calling 
`- [SFUserAccountManager notifyUserCancelledOrDismissedAuth:andAuthInfo:]` 
with `info` parameter equals nil (see [try1](https://user-images.githubusercontent.com/48205812/57375858-338f0980-71a7-11e9-82a8-6051183c3717.png), [try2](https://user-images.githubusercontent.com/48205812/57375883-46094300-71a7-11e9-9772-28164b677433.png)).

We use pod `'SalesforceSDKCore','7.0.0'` from source https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git. But it also reproducible on version 6.2.0.

**Comment by trooper2013** [comment] 2019-05-08 14:32
@rilchyshyn We will take a look. Meanwhile you can customize the handling of this situation by doing the following in your app delegate. 

```
UserAccountManager.shared.add(self)

extension AppDelegate : UserAccountManagerDelegate {
    func userAccountManager(accountManager userAccountManager: UserAccountManager, didFailAuthenticationWith error: Error, info: AuthInfo) -> Bool {
        // return true if error is handled. if false the SDK will use a default handler.
    }
}
```

**Comment by rilchyshyn** [comment] 2019-05-13 09:47
Thanks for the response! 
We will think about the pros and cons of implementing custom behavior instead of wait for the bug fix.
Anyway, this workaround could prevent the described crash and is very helpful.

**Comment by wmathurin** [comment] 2019-06-11 00:24
Not able to reproduce the issue.
![BadDomain](https://user-images.githubusercontent.com/1012459/59235065-77a96b80-8ba4-11e9-86f5-68aa954149c9.gif)

**Comment by wmathurin** [comment] 2019-06-11 00:27
How do you start the login flow?
Do you have the following in your `AppDelegate.swift`?
```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool
{
...

    AuthHelper.loginIfRequired {
        self.setupRootViewController()
    }
}
```

**Comment by rilchyshyn** [comment] 2019-06-14 09:06
Hello, @wmathurin 

Yes, we are using `AuthHelper.loginIfRequired`.

Please try to _Continue_ with invalid domain **twice** as I described (see [how-to-reproduce](https://user-images.githubusercontent.com/48205812/57307210-d2a2fb00-70ec-11e9-830b-b1672a1500e4.gif)).

**Comment by wmathurin** [comment] 2019-06-18 04:25
Thanks we have created a bug internally.

**Comment by wmathurin** [comment] 2019-07-17 22:31
Fixed by https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2928

**Closed by wmathurin** 2019-07-17 22:31 UTC
Labels: bug
