### ISSUE TITLE
NSInvalidArgumentException in sendActionForRequest on SFRestAPI.sharedInstance().performDelete

### ISSUE THREAD

**Issue by mikecaulley** [forcedotcom/SalesforceMobileSDK-iOS#2027] opened 2017-05-03 21:26 UTC
1. Version of Mobile SDK Used:  5.1 
2. Issue found in Native App or Hybrid App: Native Swift
3. OS Version: 10.3.1
4. Device: iPad Air 2
5. Steps to reproduce: Perform a SFRestAPI.sharedInstance().performDelete delete call 
6. Actual behavior:  object in sendActionForRequest is <> and when it hits line 240, "successBlock( object );", a NSInvalidArgumentException occurs.
7. Expected Behavior: The completion block should be called.
8. Error Log:

`(lldb) po object
<>

(lldb) po successBlock
0x00000001016f8100

2017-05-03 17:22:37.004 Mosaic Test[55651:493337] -[_NSZeroData count]: unrecognized selector sent to instance 0x618000012c50
2017-05-03 17:22:37.008 Mosaic Test[55651:493337] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_NSZeroData count]: unrecognized selector sent to instance 0x618000012c50'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000104f50b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001049b5141 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000104fc0134 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000104ed7840 ___forwarding___ + 1024
	4   CoreFoundation                      0x0000000104ed73b8 _CF_forwarding_prep_0 + 120
	5   libswiftFoundation.dylib            0x0000000106e8fca0 _TZFE10FoundationVs10Dictionary36_unconditionallyBridgeFromObjectiveCfGSqCSo12NSDictionary_GS0_xq__ + 208
	6   Mosaic Test                         0x00000001016f8162 _TTRXFo_oGSqGVs10DictionaryVs11AnyHashableP_____XFdCb_dGSqCSo12NSDictionary___ + 98
	7   SalesforceSDKCore                   0x000000010274a026 -[SFRestAPI(Blocks) sendActionForRequest:success:withObject:] + 166
	8   SalesforceSDKCore                   0x000000010274a360 -[SFRestAPI(Blocks) request:didLoadResponse:] + 96
	9   SalesforceSDKCore                   0x000000010274ebbb -[SFRestAPI replayRequestIfRequired:response:error:request:delegate:] + 1579
	10  SalesforceSDKCore                   0x000000010274e3d1 __37-[SFRestAPI enqueueRequest:delegate:]_block_invoke + 497
	11  SalesforceSDKCore                   0x0000000102724cc1 __43-[SFNetwork sendRequest:dataResponseBlock:]_block_invoke + 177
	12  CFNetwork                           0x000000010764287b __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 19
	13  CFNetwork                           0x0000000107642095 __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 143
	14  Foundation                          0x00000001044bf237 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	15  Foundation                          0x00000001044bef3b -[NSBlockOperation main] + 101
	16  Foundation                          0x00000001044bd6f7 -[__NSOperationInternal _start:] + 627
	17  Foundation                          0x00000001044b947c __NSOQSchedule_f + 198
	18  libdispatch.dylib                   0x000000010727605c _dispatch_client_callout + 8
	19  libdispatch.dylib                   0x000000010725494f _dispatch_queue_serial_drain + 221
	20  libdispatch.dylib                   0x0000000107255669 _dispatch_queue_invoke + 1084
	21  libdispatch.dylib                   0x0000000107257ec4 _dispatch_root_queue_drain + 634
	22  libdispatch.dylib                   0x0000000107257bef _dispatch_worker_thread3 + 123
	23  libsystem_pthread.dylib             0x000000010760d616 _pthread_wqthread + 1299
	24  libsystem_pthread.dylib             0x000000010760d0f1 start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
`

**Comment by sahitya8e7** [comment] 2017-05-04 02:28
I have the same issue. The rest call we are making is a PATCH request.

We compared with the last version we had, to see what has changed in this API. From what I can tell, the successBlock(object) is where the issue is. Whenever the dataResponse was nil, the API worked fine. Now the dataResponse is an empty dictionary "<>" and it fails.

**Comment by bhariharan** [comment] 2017-05-04 16:37
@mikecaulley @sahitya8e7 Could you try [this](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2030) pull request and let me know if that fixes the issue?

**Comment by mikecaulley** [comment] 2017-05-05 01:42
@bhariharan That commit does fix my issue.

**Comment by bhariharan** [comment] 2017-05-06 17:27
@mikecaulley The issue was an empty `NSData` object being passed along. Could you try [this] (https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2030) fix? It's simpler and more generic. Once you've verified, I'll get it merged in our `dev` branch and will be a part of `5.2`. Meanwhile, you could apply the fix on your version of `Mobile SDK`.

**Comment by mikecaulley** [comment] 2017-05-08 13:16
This also resolves the issue. Thanks.

**Comment by bhariharan** [comment] 2017-05-08 21:49
Fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2030).

**Closed by bhariharan** 2017-05-08 21:49 UTC
