### ISSUE TITLE
Not  getting the response for the SFRequest after re-login due oauth expiry without killing the app.

### ISSUE THREAD

**Issue by SrinivasGit049** [forcedotcom/SalesforceMobileSDK-iOS#1684] opened 2016-08-10 09:01 UTC
Please fill out the following details:
1. Version of Mobile SDK Used: 4.2
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: iOS 9.3.4
4. Device: iPad Air/iPad Air2
5. Steps to reproduce:
   Revoke the Oauth of the user in between during sending the SFRequest from the application.
   After we will get to Oauth error.
   Redirect the app to SF login screen.
   After this  try to login again with same credentials using 
   -[SFAuthenticationManager sharedManager] loginWithCompletion method
   Soon after logging in successfully,try to send one more SFRequest.
   During this period we are not getting any response for the request sent.
   But once we kill the app and again call -[SFAuthenticationManager sharedManager] loginWithCompletion and send the same SFRequest we are getting response.
6. Actual behavior: We are Not  getting the response for the SFRequest after re-login due oauth expiry without killing the app.
7. Expected Behavior: We should  get the response for the SFRequest after re-login due oauth expiry without killing the app.
8. Error Log: Access token or refresh token not found

**Comment by huminzhi** [comment] 2016-08-11 18:35
The issue is fixed or solved in latest build.

**Comment by huminzhi** [comment] 2016-08-12 16:34
Sorry accidentally closed this issue.. It's a valid bug.. working on it.

**Comment by huminzhi** [comment] 2016-08-12 18:36
The issue is fixed or solved in latest build.

**Comment by sayeeda** [comment] 2016-11-17 06:40
Please Fix this bug ASAP or let me know when it will be solved

**Comment by sayeeda** [comment] 2016-11-17 07:07
Do we have any release planned for this bug

**Comment by bhariharan** [comment] 2017-04-21 01:18
This is fixed on the `dev` branch and will be a part of our upcoming release.

**Closed by bhariharan** 2017-04-21 01:18 UTC
Labels: bug

**Comment by SrinivasGit049** [comment] 2017-08-01 07:08
We are facing this issue still after SFSDK 5.1 upgrade.
