### ISSUE TITLE
Data Fetch from smartstore is not working

### ISSUE THREAD

**Issue by SunilS123** [forcedotcom/SalesforceMobileSDK-iOS#2782] opened 2019-02-15 10:18 UTC
Please fill out the following details:

1. Version of Mobile SDK Used:  7.0.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: iOS 12.0
4. Device: iPad & IPhone
5. Steps to reproduce:
  
a) Create a soup and sync down some data using smart sync 
b) add some local data to same soup 

try to fetch data after inserting
"  newData.updateSoup(forFieldName: kSyncTargetLocal, fieldValue: true)
    newData.updateSoup(forFieldName: kSyncTargetLocallyCreated, fieldValue: true)
    newData.updateSoup(forFieldName: SObjectDataSpec.lastcreateddateLocal, fieldValue: Date())
    
    let result = self.store?.upsert(entries: [newData.soupDict], forSoupNamed: self.dataSpec.soupName)
    
    if let dict = result?.first, let soupEnteryId = dict["_soupEntryId"] as? Int {
        let data = store?.retrieve(usingSoupEntryIds: [NSNumber(value: soupEnteryId)], fromSoupNamed: self.dataSpec.soupName)
        print(data)
    }
   "
attached screen shots for reference

![screen shot 2019-02-15 at 3 36 09 pm](https://user-images.githubusercontent.com/17869039/52849981-655c7b00-3138-11e9-8f43-20cee9c3dde5.png)

![screen shot 2019-02-15 at 3 44 35 pm](https://user-images.githubusercontent.com/17869039/52850085-ae143400-3138-11e9-8712-5cdeeca801bd.png)

You can see that data is upserted to local store and soup entry id is generated 
but unable to retriev records from local store

**Note : we are using global smartstore**

**Comment by wmathurin** [comment] 2019-02-21 00:46
I use [SmartSyncExplorerSwift](https://github.com/forcedotcom/SalesforceMobileSDK-Templates/tree/master/SmartSyncExplorerSwift) and modified the `createLocalData` method in `SObjects.swift`. 

I created a new record in the app, and checked the value of data in the debugger. It worked fine for me.

<img width="1440" alt="screen shot 2019-02-20 at 4 44 02 pm" src="https://user-images.githubusercontent.com/1012459/53135149-01b6c100-352f-11e9-8753-645329f75865.png">

**Comment by wmathurin** [comment] 2019-03-22 00:19
Closing issue, since we can't reproduce it with the steps provided.

**Closed by wmathurin** 2019-03-22 00:19 UTC
