### ISSUE TITLE
User is not able to sign in. 

### ISSUE THREAD

**Issue by mkkroliks** [forcedotcom/SalesforceMobileSDK-iOS#3497] opened 2022-04-04 07:48 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 10.0.0
2. Issue found in Native App or Hybrid App: Native 
3. OS Version: 14.2 or any other. 
4. Device: iPhone 12 or any other. 
5. Steps to reproduce: Turn off wifi and try to sign in, turn on wifi and try to sign in. To make it work again user has to uninstall an app. 
6. Actual behavior: `SalesforceLoginViewController` displays web view with an error description 
7. Expected Behavior: `SalesforceLoginViewController` displays sign in fields. 
8. Error Log: 

![Simulator Screen Shot - iPhone 12 - 2022-04-04 at 09 13 26](https://user-images.githubusercontent.com/2151961/161498763-29459e32-0264-4e13-9bdc-22afb98120c1.png)

**Comment by wmathurin** [comment] 2022-04-04 23:13
Are you ever able to login?
The error in your screenshot happens when the scope requested (as defined in your bootconfig) don't match the scope defined by the connected app (as configured in the setup screen on the server).

**Comment by mkkroliks** [comment] 2022-04-05 07:17
Yes, as I wrote in description, I'm able to login, after reinstalling an app. Looks like something might be cached inside sdk and that's why I'm getting this error.

**Comment by wmathurin** [comment] 2022-04-05 17:54
Do you have to uninstall / reinstall the app or is killing the app sufficient?

**Comment by mkkroliks** [comment] 2022-04-06 08:00
Killing the app is not sufficient. I need to remove it and install it again.

**Comment by wmathurin** [comment] 2022-04-06 15:55
I'm unable to reproduce the issue.

When I go offline and try to login I get an error popup (1) or a safari error in the page itself when using advanced authentication (2).
If I get back online, and reload (I don't have to kill the app or anything), then the login screen appears.

The error you screenshot above is returned by the server - it's not generated on the client - so it must have happened when you were online.

How did you create your application?

(1) 
<img width="348" alt="Screen Shot 2022-04-06 at 8 51 10 AM" src="https://user-images.githubusercontent.com/1012459/162016019-429dc79d-6b48-4e48-b1fa-ae8258b7df89.png">

(2)
<img width="346" alt="Screen Shot 2022-04-06 at 8 50 11 AM" src="https://user-images.githubusercontent.com/1012459/162016282-18c06cf1-17d3-4496-8c98-7ce5cea9fd27.png">

**Comment by mkkroliks** [comment] 2022-04-07 09:05
I looked though a network traffic and for correctly working login process, sdk is making request using app domain specified under `SFDCOAuthLoginHost` .
![Pasted Graphic 6](https://user-images.githubusercontent.com/2151961/162162970-8b8a97de-a040-4016-8d70-6e9abc59020a.png)

For a failing flow it's making request using salesforce domain. 
![Screen Shot 2022-04-07 at 11 02 27](https://user-images.githubusercontent.com/2151961/162163020-fa8d420c-7672-42d1-96da-f524d3161311.png)

Request are sent after calling `UserAccountManager.shared.login`

**Comment by wmathurin** [comment] 2022-04-07 17:13
Can you tell us more about your connected app and custom domain configuration?

**Comment by mkkroliks** [comment] 2022-04-11 11:19
Yeah sure, what informations precisely do you want me to share, since I'm not a person who integrated this app with salesforce.

**Comment by mkkroliks** [comment] 2022-04-25 13:27
@wmathurin I wrote an email to you with a video showing a problem and whole configuration. Did you have a chance to look at it?

**Comment by bbirman** [comment] 2022-05-26 04:48
Closing this as duplicate of #3501, will post updates there

**Closed by bbirman** 2022-05-26 04:48 UTC
