### ISSUE TITLE
React-native - Salesforce mobile SDK 8.3.0 does not compile

### ISSUE THREAD

**Issue by KawaljeetSBagga** [forcedotcom/SalesforceMobileSDK-iOS#3327] opened 2021-01-18 06:44 UTC
1. Version of Mobile SDK Used: React-native 0.63.2 react-native, XCode version: 12.2 and forcereact mobile SDK version 8.3.0
2. Issue found in Native App or Hybrid App: Hybrid app
3. OS Version: 14
4. Device: iPhone simulator 11
5. Steps to reproduce: 

Followed the steps mentioned here: [https://trailhead.salesforce.com/en/content/learn/modules/mobile_sdk_react_native/mobilesdk_reactnative_create_app](url)
Clean and build from XCode

6. Actual behavior: Getting errors in SalesforceReact package. Find image attached: 
![sf_ios_error](https://user-images.githubusercontent.com/60910844/104881034-a396f080-5986-11eb-8618-258252420a13.png)

7. Expected Behavior: Should successfully run the code
8. Error Log: Please find image for errors

**Comment by wmathurin** [comment] 2021-01-19 17:40
This is a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/204.
The fix will be in the next version of Mobile SDK (version 9.0). See https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/212.

**Closed by wmathurin** 2021-01-19 17:40 UTC

**Comment by KawaljeetSBagga** [comment] 2021-01-20 06:14
It would be good if we get an ETA for version 9.0? @wmathurin

**Comment by wmathurin** [comment] 2021-01-20 21:24
9.0 should be released in the next few weeks.

**Comment by KawaljeetSBagga** [comment] 2021-01-22 14:09
@wmathurin What is the stable version of the SDK that works on both iOS and Android without any errors? Also, what React-Native version is compatible with that version?
PS: I have already read the Release page, but want to hear from you on the stable version, as 8.3 was also a stable release.

**Comment by wmathurin** [comment] 2021-01-22 18:18
@KawaljeetSBagga, the app generated with Mobile SDK 8.3 builds with XCode 11. The problem only arises in XCode 12. So the issue is not that Mobile SDK is not a stable release but rather that XCode 12 introduced a change causing that issue.

**Comment by KawaljeetSBagga** [comment] 2021-01-23 17:39
Ah ok. So that being said, any version of the SDK would cause issues on XCode 12. Please correct me if I am wrong.

**Comment by wmathurin** [comment] 2021-01-23 18:03
The fix needed is https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/212/commits/7a79d4a56337238e7769bf2e922d99f4042b8fb9 (following the recommendation outlined here https://github.com/facebook/react-native/issues/29633#issuecomment-694187116).
That fix is in dev and will be in 9.0.
