### ISSUE TITLE
How to use SFRestRequest son query from Swift 3.0

### ISSUE THREAD

**Issue by helloniklas** [forcedotcom/SalesforceMobileSDK-iOS#1871] opened 2016-12-13 12:22 UTC
I'm attempting,

        let segments: [String: Any] = ["type" : "Text", "text" : message]
        let body: [String: Any] = ["messageSegments" : [segments]]
        let query: [String: Any] = ["body": body as Any, "feedElementType" : "FeedItem" as Any, "subjectId" : groupID]

        let request = SFRestRequest(method: .POST, path: "/services/data/v37.0/chatter/feed-elements", queryParams: query)

But query needs to be [String: String]?

I also tried the SFJsonUtils.object without success﻿

**Comment by helloniklas** [comment] 2016-12-13 17:33
Only way I can get this to work is by setting up custom Objective-c classes and bridge them, like in this post, https://developer.salesforce.com/forums/ForumsMain?id=906F0000000DBhp

**Comment by bhariharan** [comment] 2016-12-13 17:36
Thanks for reporting @helloniklas. We will take a look.

**Comment by mgetzbw** [comment] 2016-12-21 19:26
@bhariharan @helloniklas I can speak to this as I was the one that annotated it. I annotated `queryParams:` as `NSDictionary<NSString*, NSString*>*` because the query params are validated and safe for a URL, by enforcing strings I ensured that the caller was responsible for sanitizing their own values and that the values could be serialized.

If it is possible to verify that passing in `NSDictionary<NSString*, id>*` is safe then it should be changed. However I consider that highly unlikely due to the amount of work to ensure that a proper URL comes out.

**Comment by helloniklas** [comment] 2016-12-21 21:06
@mgetzbw the Chatter api requires json so that simply won't work with [String : String]

**Comment by mgetzbw** [comment] 2016-12-21 21:08
@helloniklas serialize it to JSON as at string:

````swift
public func JSONStringify() -> String?{
        guard JSONSerialization.isValidJSONObject(self),
            let data = try? JSONSerialization.data(withJSONObject: self, options: []) else{
                return nil
        }
        return String(data: data, encoding: String.Encoding.utf8)
}
````

**Comment by helloniklas** [comment] 2016-12-21 21:29
@mgetzbw ok. But how do I then pass it in to the request of the param is specified as [String : String] rather than String.

**Comment by mgetzbw** [comment] 2016-12-21 21:37
@helloniklas unless I'm missing which [method you're calling](https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/quickreference_post_feed_item.htm) you're overcomplicating things:

````swift
let request = SFRestRequest(method: .POST, path: "/services/data/v37.0/chatter/feed-elements", queryParams:["feedElementType": "FeedItem", "subjectId" : groupID])
guard let bodyData = try? JSONSerialization.data(withJSONObject:body, options:[]) else{
     return
}
 request.setCustomRequestBodyData(bodyData, contentType: "application/json")
`````

**Comment by helloniklas** [comment] 2016-12-21 21:52
Ok. Not too familiar with the chatter api. I thought the json needed be nested into messageSegements as well as that's what worked. 

But why do I have to do setCustomRequestBodyData as well? And what is body in your sample above? 

Surely some chatter api will require more complex json though. Hence why others have gone through the pain of setting up custom bridge headers to get it to work from Swift.

**Comment by helloniklas** [comment] 2016-12-21 21:54
If queryParams is meant to take any json. I can't see how it can be [String : String]

**Comment by mgetzbw** [comment] 2016-12-21 21:54
@helloniklas it's a `POST` request, `body` is *never* in the URL query. In this case body is your JSON

**Comment by helloniklas** [comment] 2016-12-21 22:05
@mgetzbw thanks for clarifying. Will try this out when I'm back by my computer. I'm surprised it was working the other way at all then, as it seemed fine when I was bridging and passing this json into queryParams even for a post. 

Maybe there should be an initializer that takes the post body as well. To make the API clearer.

**Comment by mgetzbw** [comment] 2016-12-21 22:11
@helloniklas on having an overload for the body... I agree I do a lot of batch REST API calls and it would simplify my code as well.

On the other note: I wouldn't be surprised if the webserver was handling it because of either API misuse or legacy code. Regardless I would not recommend passing JSON via the Query.

**Comment by mgetzbw** [comment] 2016-12-22 18:23
@bhariharan I was going to suggest closing this... but it appears that there is a bug:

The property [`queryParams`](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/dev/libs/SalesforceSDKCore/SalesforceSDKCore/Classes/RestAPI/SFRestRequest.h#L115) is of type `NSDictionary<NSString*, NSObject*>*` when to match the declaration on the initialization method it should be `NSDictionary<NSString*, NSString*>*` let me know if you'd like me to fix that or leave it be for now

**Comment by bhariharan** [comment] 2016-12-22 19:27
@mgetzbw Could you send us a PR against the `dev` branch?

**Comment by mgetzbw** [comment] 2016-12-22 19:37
@bhariharan before I start work I should get clarification on the desired outcome. Do we want to open up the init method to take `NSDictionary<NSString*, id>*` or are we restricting `queryParams` back to `NSDictionary<NSString*, NSString*>*` or just `NSDictionary<NSString*, id>*`. My suggestion would be the first option, it should not be the SDK's job to serialize parameters for people in my opinion as that increases complexity and code size.

**Comment by bhariharan** [comment] 2016-12-22 19:41
@mgetzbw I agree. It should just be `NSDictionary<NSString*, id>*`.

**Comment by mgetzbw** [comment] 2016-12-22 19:42
@bhariharan did you see my concerns on the prior change? That signature could cause silent failure and unexpected behavior when things don't get serialized where a developer expects. I highly suggest requiring setting the body explicitly.

**Comment by bhariharan** [comment] 2016-12-22 21:18
@mgetzbw But it should work the way it is today. We do this for `POST`:

```
if (self.action.parameters.parameterStyle != CSFParameterStyleMultipart) {
            // Standard POST data.  We'll assume we can just send it as JSON.
            NSData *bodyData = [SFJsonUtils JSONDataRepresentation:self.queryParams];
            if (bodyData == nil) {
                [self log:SFLogLevelError format:@"%@: Error serializing request data to NSData object: %@",
                 NSStringFromSelector(_cmd),
                 [[SFJsonUtils lastError] localizedDescription]];
                return;
            }
            NSInputStream *(^bodyStreamBlock)(void) = ^{
                return [NSInputStream inputStreamWithData:bodyData];
            };
            self.action.parameters.bodyStreamBlock = bodyStreamBlock;
```

`[SFJsonUtils JSONDataRepresentation:self.queryParams]` does this:

```
if ([NSJSONSerialization isValidJSONObject:obj]) {
        jsonData = [NSJSONSerialization dataWithJSONObject:obj
                                        options:options 
                                          error:&err
         ];
```

Doc of `isValidJSONObject` mentions:

```
/* Returns YES if the given object can be converted to JSON data, NO otherwise. The object must have the following properties:
    - Top level object is an NSArray or NSDictionary
    - All objects are NSString, NSNumber, NSArray, NSDictionary, or NSNull
    - All dictionary keys are NSStrings
    - NSNumbers are not NaN or infinity
 Other rules may apply. Calling this method or attempting a conversion are the definitive ways to tell if a given object can be converted to JSON data.
 */
```

So, `id` should work, right?

**Comment by mgetzbw** [comment] 2016-12-22 21:25
@bhariharan it should. I was trying to avoid quirky APIs that change behavior in odd ways, that's all. It's my opinion that the SFRequest and associated machinery shouldn't be involved in creating the body for you; only sending it on. To me if we are going to support this I would much prefer a `setJSONBody:` message that takes in `NSDictionary<NSString*, id>*`. But it seems that time has past. I'll get the pull queued up against dev.

**Comment by bhariharan** [comment] 2016-12-22 21:51
@mgetzbw I agree with you. We will look into cleaning this up in a future release. Thanks for your suggestion.

**Comment by bhariharan** [comment] 2016-12-22 22:24
Fixed [here](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/1884).

**Closed by bhariharan** 2016-12-22 22:24 UTC
Labels: bug
