### ISSUE TITLE
Blue screen when changing the login to Sandbox

### ISSUE THREAD

**Issue by horatiu-potra-3pg** [forcedotcom/SalesforceMobileSDK-iOS#1673] opened 2016-07-28 09:14 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 
4.1.2

2. Issue found in Native App or Hybrid App: 
Native App

3. OS Version:
iOS 8 And 9

4. Device:
iPad air 2, iPad mini

5. Steps to reproduce:
 - have the login screen appear
 - tap gearbox from upper right
 - select Sandbox option

6. Actual behavior:
 - you see a blue screen

7. Expected Behavior:
 - app should permit login

8. Error Log:
2016/08/12 06:18:47.689 [4505:6603] INFO com.salesforce <SFAuthenticationManager>: Cancel authentication called.  App is currently authenticating.
line 64: function  setup(): switch user success
2016/08/12 06:18:47.695 [4505:a717] INFO com.salesforce <SFSecurityLockout>: App requested passcode screen cancel.  Screen is not displayed.

**Comment by huminzhi** [comment] 2016-08-01 19:57
@horatiu-potra-3pg will you please try our latest version 4.2? We fixed something around this area in 4.2...

**Comment by horatiu-potra-3pg** [comment] 2016-08-02 08:47
@huminzhi I updated to 4.2 and now the app doesn't crash but I get a blue screen. The only way to remove it is to kill the app and start again. The second time the Sandbox option is preserved.

Shall I close this issue and open another one ? The steps to reproduce are exactly the same as in this issue.
![img_0155](https://cloud.githubusercontent.com/assets/19264975/17322585/d1eecf60-58a6-11e6-834e-d6a8c1766c3e.jpg)

**Comment by huminzhi** [comment] 2016-08-02 18:07
Thank you @horatiu-potra-3pg , you don't need to close this and open new one..
I somehow cannot reproduce this with our sample native app: RestAPIExplorer (you can also have a try of it)..
So wondering what's your configuration, are you using userAgent login flow? Usually when you see this blue screen, it will also pop up some alert saying you cannot connect to the host for some reason.  It seems to me you are hitting some weird error and the error doesn't surface to the UI.. you can probably debug into the flow and see what's the response when it tries to connect to sandbox.. Thanks!

**Comment by huminzhi** [comment] 2016-08-03 20:11
@horatiu-potra-3pg We need a little more information to troubleshooting.. Are you seeing this on your app or our sample apps? Also before you select sandbox, do you already login with another account? And does that account has passcode enabled? Thanks to reply!

**Comment by horatiu-potra-3pg** [comment] 2016-08-04 06:02
Hello,
I can't reproduce it in RestAPIExplorer. I mention that my project is in swift, if that helps.
Sometimes I am logged in(Sandbox), in the browser but this happens when I am not logged in also.

Here are some log info, maybe it helps:
Cancel authentication called.  App is currently authenticating.
line 64: function  setup(): switch user success
INFO com.salesforce <SFSecurityLockout>: App requested passcode screen cancel.  Screen is not displayed.

**Comment by huminzhi** [comment] 2016-08-11 17:41
@horatiu-potra-3pg I tried to reproduce it with our swift template app (use forceios create -> choose native_swift), however, not able to reproduce this either... If you can share me a sample app which can reproduce this issue, it will be much much appreciated..

Actually, I looked back some issues, and it looks a lot like this one:
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1494
So, I guess you can try avoid  [[SFAuthenticationManager sharedManager] logout];` (logout) call multiple time. 

Let me know if you have some more info, meanwhile I will keep trying to reproduce it..

**Comment by huminzhi** [comment] 2016-08-17 22:27
@horatiu-potra-3pg Are you still seeing this issue.. Since I really cannot reproduce this, I am now closing this issue, however, feel free to reopen if you still have concern..

**Closed by huminzhi** 2016-08-17 22:27 UTC
Labels: investigation

**Comment by Prabuganesan** [comment] 2016-11-04 10:43
Please add following code in appdelegate class and fix this issue.

[SalesforceSDKManager sharedManager].switchUserAction = ^(SFUserAccount *fromUser, SFUserAccount *toUser) {
[weakSelf handleUserSwitch:fromUser toUser:toUser];
};
