### ISSUE TITLE
After Upgrading SDK to 7.0 many SQL Query not working in iOS App

### ISSUE THREAD

**Issue by piyushprabhakar** [forcedotcom/SalesforceMobileSDK-iOS#2743] opened 2018-12-24 10:06 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 7.0RC
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: 10.14.1
4. Device: iPhone Simulator
5. Steps to reproduce:
Below are the steps to reproduce.

1) Update SDK to 7.0
2) Resolve app Error and run the query in code or in smart store inspector.

6. Actual behavior:

After updating and resolving many SQL query which was working on previous version dosen't work. Below are some Example 
1) `Select * from {User} ` -> Qurey with * to fetch all result dosen't work.
2)` SELECT {NonCustomerTime_TVCORE__c:Id},{NonCustomerTime_TVCORE__c:SubType_TVCORE__c},{NonCustomerTime_TVCORE__c:LastModifiedDate},{NonCustomerTime_TVCORE__c:End_Date_MDE__c},{NonCustomerTime_TVCORE__c:type},{NonCustomerTime_TVCORE__c:_soupLastModifiedDate} FROM {NonCustomerTime_TVCORE__c}` -> This also Dosen't Work(![sdk comparision](https://user-images.githubusercontent.com/14050203/50396429-0873c280-0790-11e9-850a-93bd4eeffdcd.png)). it used to work with previous version 5.3.1 and 6.2), I tried in inspector as well.

It gives below Error in console

`[SFSDK] CLASS: SFJsonUtils WARNING error parsing json: Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 231." UserInfo={NSDebugDescription=Invalid value around character 231.}`

Smart Store Inspector Crashed several time on running query, After crashing if in console below error appears
`*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 2 beyond bounds [0 .. 1]'`

Advance SQL query such as inner joints also dosen't work.

All these started happening after upgrading the SDK, My code and Data is proper i have checked several time while testing the query in inspector with same data and query, The SQl query works in older SDK but it Dosen't work in newer version of SDK.

7. Expected Behavior:
8. Error Log:

**Comment by brandonpage** [comment] 2018-12-28 22:53
Hi @piyushprabhakar I am not able to reproduce this issue on my end.  Are you certain that you have successfully retrieved the data from the server?  You will get `No rows returned` if the table is empty.  

In our SmartSyncExplorer test app I was able to successfully query:
1.  `select * from {contacts}`
2.  `SELECT {contacts:Id}, {contacts:FirstName}, {contacts:LastName}, {contacts:__local__}, {contacts:__locally_created__}, {contacts:__locally_updated__}, {contacts:__locally_deleted__} FROM {contacts}`

**Comment by piyushprabhakar** [comment] 2018-12-29 14:50
Hi @brandonpage,

Below is my response,

1) Yes, Smart store has data, the Count query is showing value and if i query 2-3 row for example SELECT {user:Id}, {user:FirstName}, {user:LastName}  FROM {user} works but in case of big query i.e with around 15-20 element it dosen't work.

Many time Smart store inspector crashed with below error 

*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 2 beyond bounds [0 .. 1]'

Also whenever query via code dosen't work it returns below error

[SFSDK] CLASS: SFJsonUtils WARNING error parsing json: Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 231." UserInfo={NSDebugDescription=Invalid value around character 231.}

**Comment by wmathurin** [comment] 2019-01-08 02:06
I was able to repro the issue. The fix will be in 7.0.0 (see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2745).

**Closed by wmathurin** 2019-01-08 02:06 UTC
