### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException setObjectForKey: object cannot be nil (key: v_Data) -[SFKeychainItemWrapper setObject:forKey:]

### ISSUE THREAD

**Issue by dautovicharis** [forcedotcom/SalesforceMobileSDK-iOS#1185] opened 2015-09-11 20:21 UTC
Used salesForce SDK: SalesforceMobileSDK-iOS (3.3.0)
Device: iPhone 6
iOS: 8.2.0
JAILBREAK: NO
Environment: Production

Crash log:
Thread : Fatal Exception: NSInvalidArgumentException
0 CoreFoundation 0x0000000182d0e530 exceptionPreprocess
1 libobjc.A.dylib 0x0000000193ce40e4 objc_exception_throw
2 CoreFoundation 0x0000000182bf9348 -[__NSDictionaryM setObject:forKey:]
3 Myapp 0x00000001001f5e0c -[SFKeychainItemWrapper setObject:forKey:]
4 Myapp 0x00000001001f6748 -[SFKeychainItemWrapper setValueData:]
5 Myapp 0x0000000100274a28 +SFSecurityLockout writeLockoutTimeToKeychain:
6 Myapp 0x0000000100272784 +SFSecurityLockout upgradeSettings
7 Myapp 0x0000000100272374 +SFSecurityLockout initialize
8 libobjc.A.dylib 0x0000000193ce4bd0 _class_initialize
9 libobjc.A.dylib 0x0000000193cec9ac lookUpImpOrForward
10 libobjc.A.dylib 0x0000000193cf7db8 _objc_msgSend_uncached_impcache
11 Myapp 0x0000000100241734 -SFAuthenticationManager retrievedIdentityData
12 Myapp 0x000000010023df20 -SFAuthenticationManager loggedIn:
13 Myapp 0x00000001002423fc __62-[SFAuthenticationManager populateDefaultAuthErrorHandlerList]_block_invoke494 (SFAuthenticationManager.m:958)
14 Myapp 0x00000001002426b0 -SFAuthenticationManager processAuthError:authInfo:
15 Myapp 0x0000000100243644 -SFAuthenticationManager oauthCoordinator:didFailWithError:authInfo:
16 Myapp 0x000000010025182c -SFOAuthCoordinator notifyDelegateOfFailure:authInfo:
17 Myapp 0x0000000100254e40 -SFOAuthCoordinator refreshFlowConnectionTimerFired:
18 Foundation 0x0000000183c07514 __NSFireTimer
19 CoreFoundation 0x0000000182cc6c20 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION
20 CoreFoundation 0x0000000182cc68d0 __CFRunLoopDoTimer
21 CoreFoundation 0x0000000182cc431c __CFRunLoopRun
22 CoreFoundation 0x0000000182bf11f4 CFRunLoopRunSpecific
23 GraphicsServices 0x000000018c0136fc GSEventRunModal
24 UIKit 0x000000018758210c UIApplicationMain
25 Myapp 0x00000001000939a8 main (main.m:13)
26 libdyld.dylib 0x0000000194362a08 start

**Comment by wmathurin** [comment] 2015-09-14 19:11
Looks like a duplicate of
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1064

**Closed by wmathurin** 2015-09-14 19:11 UTC
