### ISSUE TITLE
Error in the SFkeychainItemWrapper

### ISSUE THREAD

**Issue by aeisses** [forcedotcom/SalesforceMobileSDK-iOS#1740] opened 2016-09-15 19:33 UTC
An error is occurring in my test suite when running in XCode 8.

1. Version of Mobile SDK Used: 
4.3.1
2. Issue found in Native App or Hybrid App:
Native
3. OS Version:
10.0.1
4. Device:
Simulator
5. Steps to reproduce:
I receive this error when I run my tests. I am using the Kiwi test platform and this error is failing the first test.
6. Actual behavior:
The first test in my list fails.
7. Expected Behavior:
This error does not happen and all the tests pass
8. Error Log:
ERROR com.salesforce <SFKeychainItemWrapper>: writeToKeychain: Error adding keychain item: Unknown status code (-34018).

**Comment by khawkins** [comment] 2016-09-16 18:19
Duplicate of #1655 .  Please track that issue for updates, and see the thread for workarounds.

**Closed by khawkins** 2016-09-16 18:19 UTC
Labels: bug
