### ISSUE TITLE
CustomSyncup Target will create duplicate record when we edit record while syncing.

### ISSUE THREAD

**Issue by SunilS123** [forcedotcom/SalesforceMobileSDK-iOS#2643] opened 2018-09-12 10:41 UTC
1. Version of Mobile SDK Used: 6.2.0
2. Issue found in Native App or Hybrid App: Native - Swift
3. OS Version: 11.4.1
4. Device: Ipad 
5. Steps to reproduce: 
create a  CustomSyncup Target for a table(soup). edit same record while syncing before "cleanAndSaveInLocalStore" method calls. Then it will create a duplicate record.

**Comment by wmathurin** [comment] 2018-09-12 18:40
Looks like a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2632

**Closed by wmathurin** 2018-09-12 18:40 UTC
