### ISSUE TITLE
The Salesforce classic page  sometimes appears after login.

### ISSUE THREAD

**Issue by Minrit** [forcedotcom/SalesforceMobileSDK-iOS#3388] opened 2021-05-20 10:16 UTC
1. Version of Mobile SDK Used: 9.0.0
2. Issue found in Native App or Hybrid App: React Native
3. OS Version: 14.4
4. Device: iPhone 12 Pro Max
5. Steps to reproduce: 
    1. Open the app.
    2. The login page appears.
    3. Enter the username and the password, click login.
    4. The authorization page shows up, click allow.
    5. The salseforce classic page  sometimes appears.
6. Actual behavior: The salseforce classic page appears after login.
7. Expected Behavior: The page defined in the React Native should appear.
8. Error Log: None.

**Comment by amiramelzam** [comment] 2021-10-10 11:20
We have the same issue on multiple apps ios, using salesforce sdk, its very random and very difficult to reproduce, its very critic for us.

**Comment by fobin** [comment] 2021-11-18 16:19
Same issue with our app. Really randomly feedback from clients that this happens.

**Comment by amiramelzam** [comment] 2021-12-27 11:09
Is there any news related to this issue?
This is very impacting on our clients

**Comment by Minrit** [comment] 2021-12-27 11:33
@amiramelzam Since the login page is a web view, we believe that this is a Salesforce platform issue. Our workaround is to add a refresh button that can let the user log in again on the top blue bar.

**Comment by gkotula** [comment] 2022-08-29 17:10
Hi all, apologies for taking so long to respond, but is this still an issue people are running into with the latest Mobile SDK versions?

**Comment by AnuragTiwari1** [comment] 2022-10-13 05:56
Hi @gkotula , I am still facing this one with Mobile SDK Version 10.1.1 (current latest), but don't know the steps or exact condition to reproduce it consistently

**Comment by wmathurin** [comment] 2023-12-21 19:44
Closing the issue since it's quite old. Please re-open an issue if it is still happening on the latest version of Mobile SDK.

**Closed by wmathurin** 2023-12-21 19:44 UTC

**Comment by LoganTann-pro** [comment] 2026-04-29 15:48
I'm experiencing this issue and we got many reports of users who gets this issue.

Unfortunately, its extremely random and I could not get a way to reproduce it perfectly...
