### ISSUE TITLE
MDM configuration of AppServiceHosts broke in 7.3

### ISSUE THREAD

**Issue by pbenschop** [forcedotcom/SalesforceMobileSDK-iOS#3071] opened 2019-10-30 21:51 UTC
At least for our application. I had to revert commit db0a6f96f3419c8e50875950f9145ed5afcf4abd (Fixing bug with custom login host updates) and rebuild 7.3 libSalesforceSDKCore.a to resolve the problem. The problem was that the setting of the AppServiceHosts property when configured using MDM with AirWatch, was being ignored.

**Comment by bbirman** [comment] 2019-11-16 01:03
Hi @pbenschop, do you have a host configured with SFDCOAuthLoginHost in your info.plist in addition to AppServiceHosts?

**Comment by pbenschop** [comment] 2019-11-16 01:22
Hi @bbirman, thank you for responding. Airwatch is configured with AppServiceHostLabels and AppServiceHosts. The plist of the app itself contains an SFDCOAuthLoginHost entry but no AppServiceHosts.

**Comment by bbirman** [comment] 2019-11-16 20:12
Thanks for the info! It looks like we have a bug where the plist entry is taking precedence over the MDM configuration. The intended behavior is that you should either use SFDCOAuthLoginHost or MDM hosts/labels, and MDM will take precedence if both are present. #3090 should fix this and will be in 8.0.

**Comment by pbenschop** [comment] 2019-11-16 21:49
Thanks so much for looking into this, @bbirman!

**Closed** 2019-11-16 22:50 UTC
Labels: bug
