### ISSUE TITLE
SFSyncState not showing error which occurred in "SFMobileSyncNetworkUtils" class in iOS

### ISSUE THREAD

**Issue by adijazz91** [forcedotcom/SalesforceMobileSDK-iOS#3599] opened 2023-05-25 11:25 UTC
Please fill out the following details:

1. Version of Mobile SDK Used:  10.2.0
2. Issue found in Native App or Hybrid App: Native(Objective-C)
3. OS Version: iOS 16.0
4. Device: iPad mini(6th gen)
5. Steps to reproduce: When I try to syncup my soup through SFSyncOPtion Method. My soup sync is getting failed but SDK is showing "SFSyncState" as "isDone", whereas the below calls from SFMobileSyncNetworkUtils is showing error

CLASS: SFMobileSyncNetworkUtils sendRequestWithMobileSyncUserAgent:response:

[MobileSync] CLASS: SFMobileSyncNetworkUtils sendRequestWithMobileSyncUserAgent:response:(
        {
        errors =         (
                        {
                fields =                 (
                    "gii__SalQt__c"
                );
                message = "Unable to create/update fields: gii__SalQt__c. Please check the security settings of this field and verify that it is read/write for your profile or permission set.";
                statusCode = "INVALID_FIELD_FOR_INSERT_UPDATE";
            }
        );
        id = b7j9l1234560RK8AAM;
        success = 0;
    }
)

I tried with workbench it was working. My point is 
"SFSyncState" must throw an Failed status.

6. Actual behavior: SFSyncState* sync is showing false status of Done.
7. Expected Behavior: Error from "SFMobileSyncNetworkUtils" should bypass or delegate to SFSyncState as Failed.
8. Error Log: Attaching files

[Logs_SyncState_Error.pdf](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/11564177/Logs_SyncState_Error.pdf)
[Logs_SyncState_Error_SFSyncOption.pdf](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/11564178/Logs_SyncState_Error_SFSyncOption.pdf)

**Comment by wmathurin** [comment] 2023-06-12 22:17
This is the behavior by design:
- the sync operation is marked as failed only if it could not go through all the records it needed to sync up, so done does not mean everything was saved successfully but rather that we were able to attempt to save all locally created/updated/deleted records.
- the sync operations does not stop if some records don't save, but the record will remain in their "dirty" state and their __last_error__ field will have the error returned by the server. Therefore you can query them after all to see if there were issues.

**Closed by wmathurin** 2023-06-12 22:17 UTC
