### ISSUE TITLE
forceios create react_native package.json issue

### ISSUE THREAD

**Issue by dsanvita** [forcedotcom/SalesforceMobileSDK-iOS#1661] opened 2016-07-20 17:06 UTC
1. Version of Mobile SDK Used: 4.2
2. Issue found in Native App or Hybrid App: React Native

Your react_native package.json template causes an issue when doing a forceios create for react_native because react 15.2 is not compatible with react-native 0.27.2, which says it requires 15.1:

I replaced

  "dependencies": {
    "react": "^15.1.0",
    "react-native": "^0.27.2"
  }

with

  "dependencies": {
    "react": "15.1.0",
    "react-native": "0.27.2"
  }

and it seems to have worked

**Comment by dsanvita** [comment] 2016-07-21 05:47
I think this is because react-native has react as a peerDependency:

  "peerDependencies": {
    "react": "15.1.0"
  }

So doesn't that mean that the generated project shouldn't have a dependency on react, only on react-native because it's peer dependency will pull in the right version of react?

**Comment by huminzhi** [comment] 2016-07-22 18:36
The issue is fixed in build:MobileSDK.iOS.4.3

**Closed by huminzhi** 2016-07-22 18:36 UTC
Labels: bug
