### ISSUE TITLE
Unable to request compressed data through SFRestRequest

### ISSUE THREAD

**Issue by nosarj** [forcedotcom/SalesforceMobileSDK-iOS#1688] opened 2016-08-15 10:28 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 4.2
2. Issue found in Native App or Hybrid App: Native
3. OS Version: 9.3
4. Device: iPad Retina

I have added the following header to my SFRestRequest object:

```
SFRestRequest *request = [[SFRestAPI sharedInstance] requestForQuery:query];

[request setHeaderValue:@"gzip" forHeaderName:@"Accept-Encoding"];

```
However the data still comes from salesforce uncompressed.

**Comment by huminzhi** [comment] 2016-08-22 18:32
@nosarj I am not able to reproduce this.. the response I got is compressed.. (see the screen shot below)
<img width="295" alt="screen shot 2016-08-22 at 9 49 00 am" src="https://cloud.githubusercontent.com/assets/992106/17866571/d27bf128-685b-11e6-91e6-49d27822ddaa.png">

However, in this [document](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_rest_compression.htm), it does mentioned: The REST API is not required to compress the response even if you have specified Accept-Encoding, but it normally does.

**Comment by nosarj** [comment] 2016-08-23 09:13
@huminzhi 

Thanks for getting back to me. 

I tested this on my app and found that even if I removed the setting of the custom header this key value was still in the response dictionary. Does this mean it was always coming down compressed?

Thanks again.

**Comment by huminzhi** [comment] 2016-08-23 16:41
@nosarj yes!

**Comment by huminzhi** [comment] 2016-08-23 16:48
@nosarj  I am closing this issue, but feel free to reopen if you still have question

**Closed by huminzhi** 2016-08-23 16:48 UTC
Labels: investigation
