### ISSUE TITLE
Error: 26 "file is encrypted or is not a database

### ISSUE THREAD

**Issue by McFlyssss** [forcedotcom/SalesforceMobileSDK-iOS#1704] opened 2016-08-23 14:40 UTC
Hello guys,
We spotted this error a while ago and it looks it's being happening lately. After a while after using the app we get the following error. Basically the database can not be initialised.
Please fill out the following details:
	1	Version of Mobile SDK Used: 4.1.1
	2	Issue found in Native App or Hybrid App: Native App
	3	OS Version: iOS 9.3
	4	Device: Simulator
	5	Steps to reproduce: Initialising the db several times.
	6	Actual behaviour: Showing error in logs when trying to initialise the database. The logs are the following: 
``` 
DEBUG|AppUser|Login finished notification received.
2016-08-23 16:29:53:911 DEBUG|SFSmartStore|initWithName:user:isGlobal: defaultStore, user:XXX, isGlobal: 0 
2016-08-23 16:29:53:911 INFO|SFSmartStoreUpgrade|Migrating stores from legacy locations, where necessary. 
2016-08-23 16:29:53:911 INFO|SFSmartStoreUpgrade|Legacy SmartStore directory does not exist. Nothing to do. 
2016-08-23 16:29:53:911 INFO|SFSmartStoreUpgrade|No legacy stores to migrate.
2016-08-23 16:29:53:911 INFO|SFSmartStoreUpgrade|Updating encryption method for all stores, where necessary. 
2016-08-23 16:29:53:911 INFO|SFSmartStoreUpgrade|Number of stores to update: 1 
2016-08-23 16:29:53:912 INFO|SFSmartStoreUpgrade|Store 'defaultStore' is already using the current encryption scheme. Skipping. 
2016-08-23 16:29:53:917 ERROR|SF_FMDatabase|DB Error: 26 "file is encrypted or is not a database" 
2016-08-23 16:29:53:917 DEBUG|SF_FMDatabase|DB Query: SELECT name FROM sqlite_master LIMIT 1 
2016-08-23 16:29:53:917 DEBUG|SF_FMDatabase|DB Path: /.../stores/defaultStore/store.sqlite
```
	
7	Expected Behavior:
8	Error Log:

Any clue to understand why is this happening?

Thanks in advance

**Comment by huminzhi** [comment] 2016-08-23 16:47
it's a duplicate of this issue:
https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/190
In short, it's a simulator only issue.. please try on device and confirm it's working ok

**Comment by McFlyssss** [comment] 2016-08-24 08:21
Hi @huminzhi ! 

Yesterday I was not able to find this issue. Thanks for the link. It's exactly the same problem we have.

Thanks!

**Comment by kchitalia** [comment] 2016-08-24 18:14
Closing this as its a duplicate of an existing issue.

**Closed by kchitalia** 2016-08-24 18:14 UTC
