### ISSUE TITLE
SmartStore build error in iOS 11 and Xcode 9

### ISSUE THREAD

**Issue by joaomvfsantos** [forcedotcom/SalesforceMobileSDK-iOS#2094] opened 2017-06-24 10:44 UTC
1. Version of Mobile SDK Used: 5.1.0
2. Issue found in Native App or Hybrid App: Native App
3. OS Version: iOS 11
4. Device: iPhone 7
5. Steps to reproduce: Integrate SmartStore via Cocoapods
6. Actual behavior: Should build successfully
7. Expected Behavior: Build fails with error: ```Implicit declaration of function 'sqlite3_rekey' is invalid in C99```
8. Error Log:

```
(...)/Pods/SmartStore/external/fmdb/src/fmdb/FMDatabase.m:375:14: error: implicit declaration of function 'sqlite3_rekey' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    int rc = sqlite3_rekey(_db, [keyData bytes], (int)[keyData length]);
             ^
(...)/Pods/SmartStore/external/fmdb/src/fmdb/FMDatabase.m:375:14: note: did you mean 'sqlite3_reset'?
In module 'SQLite3' imported from (...)/Pods/SmartStore/external/fmdb/src/fmdb/FMDatabase.m:9:
/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk/usr/include/sqlite3.h:4466:16: note: 'sqlite3_reset' declared here
SQLITE_API int sqlite3_reset(sqlite3_stmt *pStmt);
               ^
(...)/Pods/SmartStore/external/fmdb/src/fmdb/FMDatabase.m:401:14: error: implicit declaration of function 'sqlite3_key' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    int rc = sqlite3_key(_db, [keyData bytes], (int)[keyData length]);
             ^
(...)/Pods/SmartStore/external/fmdb/src/fmdb/FMDatabase.m:401:14: note: did you mean 'sqlite3_rekey'?
(...)/Pods/SmartStore/external/fmdb/src/fmdb/FMDatabase.m:375:14: note: 'sqlite3_rekey' declared here
    int rc = sqlite3_rekey(_db, [keyData bytes], (int)[keyData length]);
             ^
2 errors generated.
```

My Podfile looks as follows, using cocoa pods 1.2.1

```
source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'projectx' do
  use_frameworks!

  pod 'SalesforceSDKCore'
  pod 'SmartStore'

end
```

**Comment by wmathurin** [comment] 2017-06-26 13:47
We don't support iOS 11 yet. We will let you know when we do.

**Comment by joaomvfsantos** [comment] 2017-06-26 14:34
Thank you. Looking forward for that.

**Comment by wmathurin** [comment] 2017-07-12 00:11
The issue is caused by https://github.com/ccgus/fmdb/issues/591

**Comment by joaomvfsantos** [comment] 2017-07-12 07:06
Hello @wmathurin I can confirm this. Just as a side note, I would like to use Salesforce Mobile SDK as a cocoapods dependency and this means I need to manually add the SDK to change the import statement (otherwise it will be overwritten at each pod install). Since I'm in no urgency I will wait for updates on the cocoapods library, and resort to manually adding the SDK in the meanwhile. Thanks again

**Comment by iandrosov** [comment] 2017-07-12 19:08
I see this same exact error while trying to install build Mobile SDK on my macOS to do development with Native templates.
SalesforceMobileSDK-iOS/external/fmdb/src/fmdb/FMDatabase.m:375:14: error: implicit declaration of function 'sqlite3_rekey' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
     [exec]     int rc = sqlite3_rekey(_db, [keyData bytes], (int)[keyData length]);

1. Version of Mobile SDK Used: 5.2.0
2. Issue found in SDK build scripts
3. OS Version: macOS 10.12.5
4. Device: macbook Pro
5. Steps to reproduce: Integrate SmartStore via Cocoapods
6. Expected behavior: SDK Should build successfully
7. Actual Behavior: Build fails with error: Implicit declaration of function 'sqlite3_rekey' is invalid in C99

I have main Xcode 8 as dev tool and have also beta Xcode 9 installed on this Mac machine possible this causes the issue?

**Comment by wmathurin** [comment] 2017-07-12 19:16
FMDB is importing the system sqlite3.h which is different on Xcode 9 and Xcode 8.
Please see https://github.com/ccgus/fmdb/issues/591

**Comment by wmathurin** [comment] 2017-07-14 18:59
The issue is fixed in dev. See https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2125 and https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2130.

**Closed by wmathurin** 2017-07-14 18:59 UTC
