### ISSUE TITLE
Touch ID is not authenticated when changing time on iOS16.4

### ISSUE THREAD

**Issue by ryukooo** [forcedotcom/SalesforceMobileSDK-iOS#3581] opened 2023-04-11 08:00 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 10.1
2. Issue found in Native App or Hybrid App:Native App 
　Salesforce  Application
4. OS Version:16.4
5. Device:ipone X
6. Steps to reproduce:Enable the application lock of the connected application and lock the authentication with TouchID.
If you manually advance the time on iOS and then return the time and then open the Salesforce application, the TouchID authentication will not be displayed and you will not be able to cancel it.
Actual behavior:TouchID authentication is not displayed and cannot be canceled.
The event did not occur in iOS16.2.
7. Expected Behavior:TouchID authentication should be displayed.
8. Error Log:
　Success pattern without changing time
　
![image](https://user-images.githubusercontent.com/28751562/231099795-fd7910eb-bf3b-47d0-886a-2cbf05865615.png)

　Error pattern that changes the time

![image](https://user-images.githubusercontent.com/28751562/231099853-40448087-01aa-4e2b-8a97-0734543f3423.png)

**Comment by wmathurin** [comment] 2023-05-12 23:03
Could you explain step 5 in more details.
For instance if the actual time is 10:00am. What are you doing exactly? Are you opening the application with the time changed?

**Comment by ryukooo** [comment] 2023-05-22 11:14
@wmathurin 
Thanks.

There seems to be a small number of users who advance their terminal for an arbitrary amount of time, say 5 minutes.

**Comment by wmathurin** [comment] 2024-06-21 18:21
@ryukooo we have decided to close this issue without addressing it.
Even though, there might be a way to gracefully handle the manual time change (with [this](https://developer.apple.com/documentation/uikit/uiapplicationsignificanttimechangenotification) possibly), we feel that the issue is too marginal.

**Closed by wmathurin** 2024-06-21 18:21 UTC
