### ISSUE TITLE
OAuth Authenticate using refresh token not being trigger on SDK Launch (v3.1)

### ISSUE THREAD

**Issue by oliverwoolgar** [forcedotcom/SalesforceMobileSDK-iOS#969] opened 2015-03-25 18:20 UTC
I have recently updated to the 3.1 release and found that the oauth authenticate with a refresh token does not seem to be triggered any more on app launch or when bringing application back to foreground. It seems like the logic skips authentication entirely if credentials were previously stored. This causing problems when I reactivate my native app from back ground and my session has expired as a new token is not retrieved.

Is there any additional steps I need to make to get this work flow functioning again?

**Comment by khawkins** [comment] 2015-03-25 18:28
It's working as designed.  Because there are any variety of schemas for refresh token expiration, we've moved away entirely from refreshes that don't come as the result of an expired session.  Otherwise, you simply end up in scenarios where you prematurely invalidate the existing session, because the refresh token itself comes back as invalid.  This is especially evident on Connected Apps who set the refresh token policy such that the refresh token *never* works.

The native and hybrid frameworks should be able to automatically respond to expired sessions, and replay those requests, re-load the hybrid page in question, etc.  What kinds of specific problems are you having when the access token expires?

**Comment by oliverwoolgar** [comment] 2015-03-25 18:59
Our app does not go through the force.com ios SDK to send REST requests to
SF we use our own AFNetworking and request mapping implementation. This
basic implementation assumes the the token, authentication, refresh etc
work has been handled prior to sending the request and does not have a
replay feature because of this assumption.

Previously using earlier versions of the sdk the app would refresh its
token on launch and being brought to the foreground. When this happened our
request framework "listened" to the force.com ios SDK authentication events
and then updated our request framework to the new tokens so that requests
would happily go through. Because the SDK work flow has changed in terms of
when it authenticates our framework will no longer gets a new token when
required.

**Comment by khawkins** [comment] 2015-03-25 20:28
You can manually make calls to `[[SFAuthenticationManager sharedManager] loginWithCompletion:failure:]` on your launch and foregrounding events, if you like.  That will trigger the refresh the tokens, which should achieve what you're looking for.

I'm going to close this out, but if you'd like to discuss more details around implementation, feel free to reach out on our [Google Plus community](http://sfdc.co/mobilesdkcommunity).

**Closed by khawkins** 2015-03-25 20:28 UTC

**Comment by oliverwoolgar** [comment] 2015-03-25 20:31
Thanks for the information. Your reasoning makes sense and I am looking
into updating our request framework to work in the same way as the SDK.

On Mar 25, 2015, at 1:28 PM, Kevin Hawkins <notifications@github.com> wrote:

You can manually make calls to [[SFAuthenticationManager sharedManager]
loginWithCompletion:failure:] on your launch and foregrounding events, if
you like. That will trigger the refresh the tokens, which should achieve
what you're looking for.

I'm going to close this out, but if you'd like to discuss more details
around implementation, feel free to reach out on our Google Plus community
<http://sfdc.co/mobilesdkcommunity>.

—
Reply to this email directly or view it on GitHub
<https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/969#issuecomment-86203452>
.
