### ISSUE TITLE
tel link not working after upgrading Salesforce SDK 3.1

### ISSUE THREAD

**Issue by manish-metacube** [forcedotcom/SalesforceMobileSDK-iOS#932] opened 2015-02-12 11:19 UTC
Hi All, 

I have got another issue in my 3.1 SDK based application. In my app if I am having a link like 

<pre> &lt;a href="tel:13223434"&gt;  123123 &lt;/a&gt; </pre>

When i click these link continuously, it crashes Webview and take me to error page that i have configured in bootconfig.json. I have tried to execute native dialer code as well, but it also have same behaviour. 

I have already added 
<access origin="tel:*" launch-external="yes"/>
based on 
http://stackoverflow.com/questions/26271313/tel-sms-and-mailto-no-longer-working-in-android-after-upgrading-to-cordo 
to my config.xml file. But no result.  What next? 

How to resolve this issue?  

Can anybody help me. It's VERY VERY urgent?

Regards,
Manish Kumar

**Comment by khawkins** [comment] 2015-02-12 16:46
When you say you've tried the native dialer too, are you saying that both native and hybrid Mobile SDK apps crash when trying to access the dialer?

**Comment by bhariharan** [comment] 2015-02-12 20:35
@manish-metacube Is this an ```Android``` issue or ```iOS```? Please post ```Android``` issues [here](https://github.com/forcedotcom/SalesforceMobileSDK-Android).

**Comment by manish-metacube** [comment] 2015-02-13 06:37
@bhariharan This is issue for iOS. I haven't tried on android. 

@khawkins plugin is for native dialer, I have developed a native plugin that dials natively. Here is my plugin code to dial a number natively 
<pre>
- (void)openDialer:(CDVInvokedUrlCommand*)command
{
    //Get Reference of Argument array.
    NSArray * arguments = command.arguments;
    if(arguments && [arguments count] > 0)
    {
        //Get phone number
        NSString* phoneNumber = [arguments objectAtIndex:0];
        
        //check for current device. 
        UIDevice *device = [UIDevice currentDevice];
        if ([[device model] isEqualToString:@"iPhone"] )  //If it's iPhone the dial the number
        { 
            //dial phone number.
            [[UIApplication sharedApplication] openURL:[NSURL URLWithString:[NSString stringWithFormat:@"tel:%@", phoneNumber]]];
        }
    }
}

</pre>

In hybrid approach I have tried following solutions : 
<code>
window.open('tel:12223232', '_system');  
or 
window.open('tel:12223232');  

or 
&lt;a href="tel:12112121"&gt;121212 &lt;/a&gt;
</code>

In both (native and hybrid) approach. It's crashes the Webview. and  execute "loadErrorPageWithCode" method of HybridViewController and launches errorPage. 

For tracking purpose i have put tel link code on "AccountEditor" example of Mobile SDK. Here is screenshot of error what I got
![screen shot 2015-02-13 at 12 03 09 pm](https://cloud.githubusercontent.com/assets/2398709/6183233/94808044-b378-11e4-96b8-eb457f2ad1e3.png)

I hope above will help you to understand the issue.

**Comment by manish-metacube** [comment] 2015-02-13 06:40
Some time It will not throw error first time, but if you continue to click on tel link after 3-4 steps you will receive the error.

**Comment by stvnhg** [comment] 2015-04-15 14:45
Any update on this? The "tel:0292" a href link works in hybrid Android version but not on hybrid iOS. Sends me straight to the error.html page and users have to kill and relaunch the app..

**Comment by manish-metacube** [comment] 2015-04-16 06:49
@stvnhg ,

Here is a workaround
 Go to <code>Platform/ios/CordovaLib/Classes/CDWebViewDelegate.m   </code>
then go to <code> (BOOL)webView:(UIWebView*)webView shouldStartLoadWithRequest </code>  in this method look for the <code>switch (_state)  </code> 

on <code>default:</code> comment following code
                <br/>    <Code>       if ([_delegate respondsToSelector:@selector(webView:didFailLoadWithError:)]) {
                            NSDictionary* errorDictionary = @{NSLocalizedDescriptionKey : description};
                            NSError* error = [[NSError alloc] initWithDomain:@"CDVWebViewDelegate" code:1 userInfo:errorDictionary];
                            [_delegate webView:webView didFailLoadWithError:error];
                        } 
 </code>

Now rebuild your project, That's ALL. 

Be careful whenever you recreate ios platform you need to repeat this step.

**Comment by stvnhg** [comment] 2015-04-16 07:32
@manish-metacube Thanks but that didn't work. Same result.

**Comment by manish-metacube** [comment] 2015-05-29 07:04
@stvnhg ,
Can you add case for <code>STATE_WAITING_FOR_LOAD_START </code> before <code>default:</code>?
<pre>
case STATE_WAITING_FOR_LOAD_START:
         NSLog(@"CDVWebViewDelegate: Unexpected didFinish while waiting for load start.");
         break;
</pre> 
Please try and let me know

**Comment by akhileshgupta** [comment] 2015-06-19 05:30
This looks like a change in behavior of cordova. Can you check if you are able to reproduce this with plain cordova app without Mobile SDK plugins? Also try using `<meta name="format-detection" content="telephone=yes">` in your webpage.

I am closing this issue as this is outside Mobile SDK's control. Please reopen if the issue doesn't appear with a plain cordova app.

**Closed by akhileshgupta** 2015-06-19 05:30 UTC
Labels: bug
