### ISSUE TITLE
Fatal Crashes - Keychain

### ISSUE THREAD

**Issue by geekandt** [forcedotcom/SalesforceMobileSDK-iOS#2988] opened 2019-09-06 00:09 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: MobileSDK 6.2.0
2. Issue found in Native App or Hybrid App:
Hybrid App 

3. OS Version:
iOS 10 and above
4. Device: All devices
5. Steps to reproduce: 
Over 8000 crashes in last 7 days, for iOS users mostly on 2.17.0 and 2.17.1 app builds, with Fatal Exception: com.salesforce.security.keychainException

We are seeing an extremely large spike in iOS crashes that are apparently caused by the SF Mobile SDK trying to read sensitive information from the keychain. Our iOS dev team has investigated and their initial conclusion is because of the current permission level the phone won’t allow it and as result the app will crash.

It is unknown exactly what the customer experience is, other than fatal crash. We are not sure if the crash is “only” happening in the background app state, or if this is foreground. Regardless, we would like to solve the issue quickly as possible.

6. Actual behavior:
7. Expected Behavior:
8. Error Log:
 .png screenshot too for context of what Crashlytics looks like.
![Crashlytics](https://user-images.githubusercontent.com/43869408/64392043-a0df7800-d07d-11e9-9901-602b8633ac25.png)

Crash report
[iOS SF Fatal Crash - 2019-08-26 - All Threads.txt](https://github.com/forcedotcom/SalesforceMobileSDK-iOS/files/3581659/iOS.SF.Fatal.Crash.-.2019-08-26.-.All.Threads.txt)

Also, our devs have the following questions:

Is it possible to remove the SDK's dependency on the keychain?
Is it possible to change the security level so that the SDK can access the keychain in background state?
3a. What is the Silent Notification from SF generally used for? What purpose does it serve?
3b. If possible, while the app is backgrounded, would it help if the app ignore the Silent Notification from SF (or have the app "do nothing" should it receive a SF-generated Silent Notification), provided there is no adverse flow-on UX impact.

**Comment by trooper2013** [comment] 2019-09-06 16:49
@geekandt version of Mobile SDK Used: 218.0.1? Which version of mobile SDK are you using. We have no version like the one you have reported. Mobile SDK uses Keychain to store sensitive information. It is a security requirement. Mobile SDK cannot be used without keychain. To change the access level permissions in the SDK, use [SFKeychainItemWrapper setAccessibleAttribute:] in the AppDelegate to relax the permissions. [Read here](https://developer.apple.com/documentation/security/ksecattraccessiblewhenunlockedthisdeviceonly?language=objc)

**Comment by geekandt** [comment] 2019-09-08 23:20
Hi @trooper2013 , sorry, that's the version for the serviceSDK. will ask the devs what is the version of mobileSDK.

Thanks for that information. 
Would like to ask what are the possible reasons of the fatal crashes?
Also, our devs have the following questions:

3a. What is the Silent Notification from SF generally used for? What purpose does it serve?
3b. If possible, while the app is backgrounded, would it help if the app ignore the Silent Notification from SF (or have the app "do nothing" should it receive a SF-generated Silent Notification), provided there is no adverse flow-on UX impact.

**Comment by geekandt** [comment] 2019-09-10 05:08
@trooper2013  Mobile SDK version is MobileSDK 6.2.0

**Comment by geekandt** [comment] 2019-09-12 07:11
Hi @trooper2013 , any updates on the above? :)

**Comment by wmathurin** [comment] 2020-07-08 23:16
Looks like a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/2905 - closing this issue.

**Closed by wmathurin** 2020-07-08 23:16 UTC
