### ISSUE TITLE
failBlock and completeBlock are not triggered with MobileSDK 3.3 on iOS

### ISSUE THREAD

**Issue by dietmarhedden** [forcedotcom/SalesforceMobileSDK-iOS#1128] opened 2015-08-02 08:55 UTC
With Mobile SDK 3.3 on iOS neither the failBlock nor the completeBlock are triggered after calling performUpdateWithObjectType or performUpsertWithObjectType. Downgrading the project to Mobile SDK 3.1 solves the issue without code changes.

**Comment by wmathurin** [comment] 2015-08-04 18:07
We will investigate. Thanks.

**Comment by wmathurin** [comment] 2015-08-04 22:16
We are unable to reproduce the issue.
For example the test "testBlockUpdate" at line 975 of https://github.com/forcedotcom/SalesforceMobileSDK-iOS/blob/master/libs/SalesforceRestAPI/SalesforceRestAPITests/SalesforceRestAPITests.m
uses both methods without any problems.
To run the test, clone SalesforceMobileSDK-iOS, run ./install.sh and open the workspace in xcode.

**Comment by dietmarhedden** [comment] 2015-08-06 17:24
Thanks for the feedback. I will let the project team re-test the sample app in their xcode env.

**Comment by wmathurin** [comment] 2015-08-18 18:04
Closing for now. Re-open if you can reproduce the issue.

**Closed by wmathurin** 2015-08-18 18:04 UTC
Labels: bug
