### ISSUE TITLE
Forgot password link on login screen is not working

### ISSUE THREAD

**Issue by Annelies1** [forcedotcom/SalesforceMobileSDK-iOS#1912] opened 2017-02-08 11:10 UTC
Hi,

In the latest version 5.0 (and also previously in 4.3) when I press the 'Forgot password' link on the login screen, then nothing happens. 

OS Version: ios 10.1.1 
Device: ipad air 2

Steps to reproduce:
Open the login screen with SDK method from SFAuthenticationManager:

- (BOOL)loginWithCompletion:(SFOAuthFlowSuccessCallbackBlock)completionBlock
                    failure:(SFOAuthFlowFailureCallbackBlock)failureBlock
{
    return [self loginWithCompletion:completionBlock failure:failureBlock account:nil];
}

Click on the 'forgot password?' link
Actual behavior: Nothing happens. 
Expected behavior: browser opens with steps to reset password?

There are no errors in the log.

**Comment by huminzhi** [comment] 2017-02-21 19:35
The issue is fixed on the 'dev' branch.
Please try to reproduce again and see if it still exists. Thank you!

**Comment by huminzhi** [comment] 2017-02-21 22:25
The issue is fixed on the 'dev' branch.
Please try to reproduce again and see if it still exists. Thank you!

**Comment by huminzhi** [comment] 2017-02-21 22:35
The issue is fixed on the 'dev' branch.
Please try to reproduce again and see if it still exists. Thank you!

**Comment by huminzhi** [comment] 2017-02-22 19:35
The issue is fixed on the 'dev' branch.
Please try to reproduce again and see if it still exists. Thank you!

**Comment by huminzhi** [comment] 2017-02-23 19:35
The issue is fixed on the 'dev' branch.
Please try to reproduce again and see if it still exists. Thank you!

**Comment by huminzhi** [comment] 2017-02-24 19:35
The issue is fixed on the 'dev' branch.
Please try to reproduce again and see if it still exists. Thank you!

**Comment by huminzhi** [comment] 2017-02-27 19:35
The issue is fixed on the 'dev' branch.
Please try to reproduce again and see if it still exists. Thank you!

**Comment by huminzhi** [comment] 2017-02-27 19:55
The issue should be fixed on Wednesday with server side change..

**Comment by Annelies1** [comment] 2017-02-27 19:56
great, thanks!

2017-02-27 20:55 GMT+01:00 Maggie Hu <notifications@github.com>:

**Closed** 2017-02-28 04:50 UTC
Labels: bug
