### ISSUE TITLE
IDP Provider App

### ISSUE THREAD

**Issue by nzsrini** [forcedotcom/SalesforceMobileSDK-iOS#3619] opened 2023-06-23 05:34 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 10.2.0
2. Issue found in Native App or Hybrid App: Native
3. OS Version: iOS 16.2
4. Device:Phone 14 Pro & iPad Pro (12.9 inch) (6th generation)
5. Steps to reproduce:
      1. Log into idprovider app
      2. wait for session to timeout
      3. open client app and select idp flow

7. Actual behavior:
IDprovider gets "Bad_OAuth_Token" error (Invalid access token), sends this error response to client app which does not allow user to login
9. Expected Behavior:

IDprovider should refresh access token, making the login request successful, sends response to client app which allows user to login
11. Error Log:

**IDP Invalid access token**

The idp flow works fine when a user opens the idprovider app for the first time and has to enter their credentials to login. When opening a client app that creates and sends the idp login request to the idprovider the user is logged in as expected.

However the next day when testing whether the client app can be logged in using the idprovider 
we get a Bad_OAuth_Token error - which corresponds to an Invalid access token.

In the idprovider’s connected app policies the refresh token policy is ‘valid until revoked’. So we are expecting that when a client app creates the idp request the idprovider should process this request and log the client app in.

We assume that the idprovider’s access token is not being refreshed and thus is creating this error. Is there some logic we are missing in our idprovider? or possibly some connected app settings we are missing?

**Comment by bbirman** [comment] 2023-06-26 21:53
Hi @nzsrini, the IDP app should refresh like you mentioned, it looks like there might be a bug but still investigating it. I'll update when we know more

**Comment by bbirman** [comment] 2023-06-27 01:19
Confirmed that it's a bug and it should be fixed with https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/3620

**Closed by bbirman** 2023-06-27 01:19 UTC
