### ISSUE TITLE
Custom Endpoint API rest not working.

### ISSUE THREAD

**Issue by aantonyuk** [forcedotcom/SalesforceMobileSDK-iOS#2319] opened 2017-12-11 13:00 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 5.3.0
2. Issue found in Native App or Hybrid App: ReactNative
3. OS Version: iOS
4. Device: iPhone 7
5. Steps to reproduce:

forceClient.sendRequest('/services/data', '/v36.0/connect/user-profiles/userId/photo',
      (response) => {
        console.log(response);
      },
      (error) => {
        console.log(`Failed to upload user photo:${error}`);
      },
      'POST',
      {},
      { 'X-Connect-Bearer-Urls': 'true' },
      { fileUpload:
        {
          fileUrl: uri,
          fileMimeType: 'image/jpeg',
          fileName:fileName,
        },
      },
    );

6. Actual behavior:
7. Expected Behavior:
8. Error Log:

Exception '-[__NSSingleEntryDictionaryI setObject:forKey:]: unrecognized selector sent to instance 0x604000625e80' was thrown while invoking sendRequest on target SFNetReactBridge with params (
        {
        endPoint = "/services/data";
        fileParams =         {
            fileUpload =             {
                fileMimeType = "image/jpeg";
                fileName = "IMG_0002.JPG";
                fileUrl = "file:///Users/user/Library/Developer/CoreSimulator/Devices/D7695336-0D13-49B8-BCC5-D2F2CF05BE70/data/Containers/Data/Application/296EC695-5354-4D14-818D-AECA75C2EDFE/Documents/images/C404AA38-8EEE-46BB-86CB-7228755C9471.jpg";
            };
        };
        headerParams =         {
            "X-Connect-Bearer-Urls" = true;
        };
        method = POST;
        path = "/v36.0/connect/user-profiles/0057F000007S1Ih/photo";
        queryParams =         {
        };
    },
    43
)

It doesn't work at all.

**Comment by wmathurin** [comment] 2017-12-12 02:06
There is a regression indeed. Working on a fix.

**Comment by wmathurin** [comment] 2017-12-12 02:13
The issue is being addressed in dev (see https://github.com/forcedotcom/SalesforceMobileSDK-iOS/pull/2324) and will be in our soon to be released SDK 6.0.

**Closed by wmathurin** 2017-12-12 02:13 UTC
Labels: bug

**Comment by aantonyuk** [comment] 2017-12-12 05:00
@wmathurin How soon will the 6 version sdk?

**Comment by wmathurin** [comment] 2017-12-12 07:47
Should be next week #safeharbor

**Comment by aantonyuk** [comment] 2017-12-19 09:34
After upgrade to latest version 6 I have the same issue.

    net.sendRequest('/services/data', '/v41.0/connect/user-profiles/XXXXXXX/photo',
      (response) => {
        callback(response);
      },
      (error) => {
        console.log(`Failed to upload user photo:${error}`);
      },
      'POST',
      {},
      { 'X-Connect-Bearer-Urls': 'true' },
      { fileUpload: { fileUrl: response.uri, fileMimeType: 'image/jpeg', fileName: 'pic.jpg' } },
    );



    Exception '-[__NSSingleEntryDictionaryI setObject:forKey:]: unrecognized selector sent to instance 0x60000083c940' was thrown while invoking sendRequest on target SFNetReactBridge with params (
            {
            endPoint = "/services/data";
            fileParams =         {
                fileUpload =             {
                    fileMimeType = "image/jpeg";
                    fileName = "pic.jpg";
                    fileUrl = "file:///Users/xxxxx/Library/Developer/CoreSimulator/Devices/D7695336-0D13-49B8-BCC5-D2F2CF05BE70/data/Containers/Data/Application/30B7757B-3B73-422B-9B9E-9E235F56D470/Documents/images/D9B21599-CBCA-486E-8C85-7DE753FF038B.jpg";
                };
            };
            headerParams =         {
                "X-Connect-Bearer-Urls" = true;
            };
            method = POST;
            path = "/v41.0/connect/user-profiles/xxxxxxxx/photo";
            queryParams =         {
            };
        },
        43
    )

**Comment by aantonyuk** [comment] 2017-12-19 14:39
@wmathurin please help me with this issue

**Comment by wmathurin** [comment] 2017-12-19 15:55
Here is a simple react native app using Mobile SDK 6.0 to set a user picture.
Please compare with your code and you should be able to figure out the issue.

https://github.com/wmathurin/MyUserPicReactNative
