### ISSUE TITLE
Convert updateEncryptionForStore: user to public method

### ISSUE THREAD

**Issue by McFlyssss** [forcedotcom/SalesforceMobileSDK-iOS#1386] opened 2016-02-11 13:51 UTC
Hi guys,

I've been having an issue related with encryption using your SDK. I use a seed db that needs to be encrypted to be used the first time the app runs.

If the app went background during that process I was not able to resume the process.
I found out that this was happening basically because when the app failed to encrypt the db using <code>+ (void)updateEncryption</code> in <code>SFSmartStoreUpgrade</code> I was unable to detect if the process failed at some point.

What I have done at the end is create a category in my own class that makes public the method that returns a BOOL value indicating if the process finished successfully:
```objectivec
@interface SFSmartStoreUpgrade (Utils)

// This category makes this existing method public
// This method is required since -updateEncryption, which is public, does not return status

+ (BOOL)updateEncryptionForStore:(NSString *)storeName user:(SFUserAccount *)user;

@end
```
Do you think we could include this signature in the <code>SFSmartStoreUpgrade.h</code> ?

Thanks!

**Comment by khawkins** [comment] 2016-02-12 20:42
The functionality in `[SFSmartStoreUpgrade updateEncryptionForStore:user:]` was designed to serve the singular purpose of upgrading the encryption scheme of in-place SmartStore instances that are using legacy encryption schemes—or, coinciding with your use case, no encryption—from previous versions of the SDK.  I'm reluctant to say that the method should be made public, because it's part of a larger process of initializing SmartStore instances.  I.e. its design is as an inherently internal process.

How are you staging and migrating your SmartStore instance(s) in the first place?  In the scenario you describe, our recommendation would be to stick with the import functionality available via the public interfaces of SmartStore.  Namely, iterate your initial data and use `[SFSmartStore upsertEntries:toSoup:withExternalIdPath:error:]` to import your data set.  To go below that is generally to breach the public API encapsulation of SmartStore.  Is there something that precludes you from taking that approach?

**Comment by McFlyssss** [comment] 2016-02-22 10:24
Hi again,

First of all, sorry for taking so much time to answer this. I could not make it before.

In regards of using <code>[SFSmartStoreUpgrade updateEncryptionForStore:user:] </code> my problem is that the method does not return a BOOL value indicating that the process could not be finished and in some cases this happens.
To me this can go wrong when during the encryption process the app goes background. Next time the app goes foreground the method fails and we have no knowledge of it.

Then what concerns me of <code>[SFSmartStore upsertEntries:toSoup:withExternalIdPath:error:]</code> is that the seed that we include is quite big, about 80 Mb so inserting all the entities to the new encrypted db may take a long time.

Do you have any other suggestion?

**Comment by wmathurin** [comment] 2016-02-23 00:43
Are you thinking of shipping a database with the application and then re-encrypt once the user logs in?

**Comment by McFlyssss** [comment] 2016-02-23 08:22
Hello,

Yes. The app uses lots of data and we ship some data within the bundle so the user does not need to sync all the required data. What we are doing now is encrypt the file once the app starts for the first time.

Cheers

**Comment by wmathurin** [comment] 2016-02-23 22:04
Interestingly, that's the approach that was taken for the Dreamforce'15 application (which is built on top of MobileSDK/SmartStore/SmartSync). The bundled database contained public data and was not encrypted.

**Comment by wmathurin** [comment] 2016-03-16 18:23
Closing the issue - if you want more details on how the Dreamforce'15 application, let us know.

**Closed by wmathurin** 2016-03-16 18:23 UTC

**Comment by McFlyssss** [comment] 2016-03-17 15:26
Hey @wmathurin !

Absolutely. I would love to know more about that topic. Who should l ask?

Thanks again!

**Comment by wmathurin** [comment] 2016-03-17 21:03
@khawkins, would you mind giving a few pointers?

**Comment by khawkins** [comment] 2016-03-17 23:18
The Dreamforce approach was to go more directly at the underlying database more manually, since we didn't want to step into the middle of SmartStore processes.  So we made use of `SFSmartStore.storePath` to copy our bundle SmartStore DB into its proper location, `[SFSmartStore encryptionKeyBlock]` to get the encryption key, then through private category extensions exposed `[SFSmartStoreDatabaseManager openDatabaseWithPath:key:error:]` and `[SFSmartStoreDatabaseManager encryptOrUnencryptDb:name:path:oldKey:newKey:error:]`, so that we could encrypt the copied database ourselves.

I agree that it's not ideal to have to implement such low level functionality outside of the SDK.  It would be cleaner and more practical to have such functionality encapsulated into "import" and "export" SmartStore utility classes that exist inside of the Mobile SDK.
