### ISSUE TITLE
Hybrid Remote App - Error Page is not shown on no connection

### ISSUE THREAD

**Issue by alsocalledchris** [forcedotcom/SalesforceMobileSDK-iOS#2427] opened 2018-02-26 09:22 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 6
2. Issue found in Native App or Hybrid App: Hybrid
3. OS Version: iOS 11
4. Device: iPhone 6 plus/ all of them
5. Steps to reproduce: Open the Hybrid App when the device has no internet connection. 
6. Actual behavior: Bootstrap error page is shown with no connection error message
7. Expected Behavior: Custom defined error page is shown as per config
8. Error Log: NA

Works fine in Android

**Comment by bhariharan** [comment] 2018-03-06 00:42
@alsocalledchris I verified that it's pulling in the correct file using our sample app with the latest from the `dev` branch. I was unable to reproduce this issue. Could you verify that you specified the correct filename of the custom error page in your app's `bootconfig.json` and that the file is in the correct location (under the `www/` folder)?

**Comment by alsocalledchris** [comment] 2018-03-06 08:22
Hi @bhariharan - thanks for looking at this. Yes, we triple checked files and paths:

File is in root of www/ folder and called error.html and the bootconfig has the value:

"errorPage": "error.html",

Same approach with Android and it works. Does your dev branch show the error page when the App starts and there is no internet connection?

**Comment by bhariharan** [comment] 2018-03-06 18:12
@alsocalledchris When the app is started up offline, is there a valid logged in user? Or are you starting up the app from scratch in offline mode (before logging in)?

With a valid logged in user, if I start up the app later in offline mode, it correctly loads the error page.

**Comment by alsocalledchris** [comment] 2018-03-07 08:51
@bhariharan - Double checked App starting offline and with a valid logged in user (Steps: Open App, log in with user,  navigated around the App, close the App completely (swiped away), turned off the internet connection, open App). Still seeing the Bootstrap error page.

**Comment by wmathurin** [comment] 2021-05-06 23:42
This looks like a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1712

**Closed by wmathurin** 2021-05-06 23:42 UTC
