### ISSUE TITLE
Salesforce pod 3.3.0 failing in XCode 7

### ISSUE THREAD

**Issue by jdraymon** [forcedotcom/SalesforceMobileSDK-iOS#1116] opened 2015-07-24 21:43 UTC
Attempting to add the mobile SDK through cocoapods in XCode 7 beta 4 gives these two errors:

.../Pods/SalesforceMobileSDK-iOS/libs/SalesforceSDKCommon/SalesforceSDKCommon/SalesforceSDKCommon.h:31:9: 'SalesforceSDKCommon/SFSDKAsyncProcessListener.h' file not found

.../Pods/Target Support Files/SalesforceMobileSDK-iOS/SalesforceMobileSDK-iOS-prefix.pch:5:9: Could not build module 'SalesforceMobileSDK_iOS'

**Comment by vibgy** [comment] 2015-08-04 17:09
Me too. When is the support for XCode 7 coming up?

**Comment by lettergram** [comment] 2015-08-11 19:31
I've had the issue after trying to install the mobile SDK via cocoapods in XCode 7 beta 5:

> .../SalesforceMobileSDK-iOS/SalesforceMobileSDK-iOS-prefix.pch:5:9: 'SalesforceCommonUtils/SFLogger.h' file not found

**Comment by wmathurin** [comment] 2015-08-11 23:18
Xcode 7/ios 9 issues will be addressed in a upcoming patch. Exact date TBD. Should be before iOS 9 gets out of beta.

**Comment by wmathurin** [comment] 2015-08-18 21:37
I created a new project in Xcode 7 beta 5.
Added a pod file with pod 'SalesforceMobileSDK-iOS', '3.3.0'
Ran pod update and open the app's workspace.
There is no issue building or running it.
What are you doing differently?

**Comment by powerje** [comment] 2015-08-19 01:06
@lettergram are you doing `use_frameworks!` in your Podfile? I saw similar errors today attempting to build my pods as frameworks (for a today extension). I'm not sure if it's something I'm doing wrong or not.

**Comment by lettergram** [comment] 2015-08-19 01:50
@powerje I am indeed using use_frameworks!. Below is my podfile. 

## podfile

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

pod 'Alamofire', '~> 1.3'

pod 'SalesforceMobileSDK-ios'

pod 'Wit', '~>4.0.0'

**Comment by wmathurin** [comment] 2015-08-19 18:11
Because it's a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1072, I'll close this issue.

**Closed by wmathurin** 2015-08-19 18:11 UTC
Labels: bug
