### ISSUE TITLE
Problem when changing host

### ISSUE THREAD

**Issue by chompunut** [forcedotcom/SalesforceMobileSDK-iOS#1426] opened 2016-02-26 08:02 UTC
I've created a native application using SalesforceMobile SDK type native_swift.
When I login to production (login.salesforce.com) and send request using SFRestAPI.send() everything works fine then I log out and switch host to sandbox (test.salesforce.com) and sending request, the app loops to refresh token many times and no response back to SFRestAPIDelegate.

Is there something that I have to clear before log out or switching host?

Here is log after I send request via sandbox
```
**************************** HomeViewController send request
2016-02-26 14:56:48.095 MagnoliaSF[17511:10511071] A background URLSession with identifier com.salesforce.network already exists!
2016-02-26 14:56:48.778 MagnoliaSF[17511:10526179] [CSFSalesforceOAuthRefresh refreshAuthWithCompletionBlock:] INFO: initiating auth refresh.
2016-02-26 14:56:48:779 MagnoliaSF[17511:10511071] DEBUG|SFOAuthCoordinator|authenticate authenticating as 3MVG9Y6d_Btp4xp6f6cFa6P2TjTsKi0m0z_pSQ37V2uW06XbZfEBt2TUhzgV8vKUSELkUpvzW3AAowQiiO0kF with refresh token on 'https://test.salesforce.com' ...
2016-02-26 14:56:48:781 MagnoliaSF[17511:10511071] INFO|SFOAuthCoordinator|beginTokenEndpointFlow:: Initiating refresh token flow.
2016-02-26 14:56:48:782 MagnoliaSF[17511:10511071] DEBUG|SFOAuthCoordinator|beginTokenEndpointFlow: with format=json&redirect_uri=sfdc://success&client_id=3MVG9Y6d_Btp4xp6f6cFa6P2TjTsKi0m0z_pSQ37V2uW06XbZfEBt2TUhzgV8vKUSELkUpvzW3AAowQiiO0kF&grant_type=refresh_token&refresh_token=REDACTED
2016-02-26 14:56:49:542 MagnoliaSF[17511:10526177] DEBUG|SFKeychainItemWrapper|setObject:forKey: Value already stored in the keychain. No action taken.
2016-02-26 14:56:49.823 MagnoliaSF[17511:10526179] [CSFSalesforceOAuthRefresh refreshAuthWithCompletionBlock:] INFO: initiating auth refresh.
2016-02-26 14:56:49:825 MagnoliaSF[17511:10511071] DEBUG|SFOAuthCoordinator|authenticate authenticating as 3MVG9Y6d_Btp4xp6f6cFa6P2TjTsKi0m0z_pSQ37V2uW06XbZfEBt2TUhzgV8vKUSELkUpvzW3AAowQiiO0kF with refresh token on 'https://test.salesforce.com' ...
2016-02-26 14:56:49:826 MagnoliaSF[17511:10511071] INFO|SFOAuthCoordinator|beginTokenEndpointFlow:: Initiating refresh token flow.
2016-02-26 14:56:49:827 MagnoliaSF[17511:10511071] DEBUG|SFOAuthCoordinator|beginTokenEndpointFlow: with format=json&redirect_uri=sfdc://success&client_id=3MVG9Y6d_Btp4xp6f6cFa6P2TjTsKi0m0z_pSQ37V2uW06XbZfEBt2TUhzgV8vKUSELkUpvzW3AAowQiiO0kF&grant_type=refresh_token&refresh_token=REDACTED
2016-02-26 14:56:50:559 MagnoliaSF[17511:10526177] DEBUG|SFKeychainItemWrapper|setObject:forKey: Value already stored in the keychain. No action taken.
2016-02-26 14:56:50.841 MagnoliaSF[17511:10526176] [CSFSalesforceOAuthRefresh refreshAuthWithCompletionBlock:] INFO: initiating auth refresh.
2016-02-26 14:56:50:843 MagnoliaSF[17511:10511071] DEBUG|SFOAuthCoordinator|authenticate authenticating as 3MVG9Y6d_Btp4xp6f6cFa6P2TjTsKi0m0z_pSQ37V2uW06XbZfEBt2TUhzgV8vKUSELkUpvzW3AAowQiiO0kF with refresh token on 'https://test.salesforce.com' ...
```

**Comment by huminzhi** [comment] 2016-05-06 15:13
hi, @chompunut hope you already solved this issue. If not, you can refer to our RestAPIExplorer app:https://github.com/forcedotcom/SalesforceMobileSDK-iOS/tree/master/native/SampleApps/RestAPIExplorer, run it on iPad simulator, logout and switch user all work fine. You only need to call:   [[SFAuthenticationManager sharedManager] logout];

Let me know if still encounter this issue...

**Comment by huminzhi** [comment] 2016-05-06 19:51
The issue is fixed in build.

**Closed by huminzhi** 2016-05-06 19:51 UTC
Labels: investigation
