### ISSUE TITLE
Login sometimes redirect to salesforce.com home page

### ISSUE THREAD

**Issue by Roamaon** [forcedotcom/SalesforceMobileSDK-iOS#3328] opened 2021-01-19 14:42 UTC
Please fill out the following details:

1. Version of Mobile SDK Used: 8.3.0
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: 14
4. Device: iPad 7th generation
5. Steps to reproduce: 
  1) Open App with Salesforce SDK, you will see login screen ![Снимок экрана 2021-01-19 в 15 34 59](https://user-images.githubusercontent.com/58599655/105049121-0070d480-5a75-11eb-9905-0eb1dfee5393.png)
  2) Enter credentials and click login button
6. Actual behavior:
  **Sometimes** SDK redirect you to salesforce home page after login
  
![Снимок экрана 2021-01-19 в 15 32 00](https://user-images.githubusercontent.com/58599655/105049158-0b2b6980-5a75-11eb-9f6d-9bd067168a66.png)

7. Expected Behavior:

![Снимок экрана 2021-01-19 в 15 35 23](https://user-images.githubusercontent.com/58599655/105049184-11214a80-5a75-11eb-909c-875ea25266e5.png)

8. Error Log: N/A

**Comment by wmathurin** [comment] 2021-01-19 21:26
Would you mind sharing what's in your bootconfig.json? (Make sure to edit out remoteAccessConsumerKey)

**Comment by Roamaon** [comment] 2021-01-19 22:26
> Would you mind sharing what's in your bootconfig.json? (Make sure to edit out remoteAccessConsumerKey)

{
    "remoteAccessConsumerKey": "XXXXXXX" ,
    "oauthRedirectURI": "XXX:///mobilesdk/detect/oauth/done",
    "oauthScopes": ["api", "web"],
    "isLocal": true,
    "startPage": "index.html",
    "errorPage": "error.html",
    "shouldAuthenticate": true,
    "attemptOfflineLoad": true
}

The issue appears randomly 0-2 times per month without strict steps to reproduce.

**Comment by wmathurin** [comment] 2021-01-20 01:13
Looks like a duplicate of https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/466

**Comment by wmathurin** [comment] 2021-02-03 00:09
Closing this issue since it's a duplicate (keep the other [issue](https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/466) opened).

**Closed by wmathurin** 2021-02-03 00:09 UTC
Labels: duplicate

**Comment by iowlit** [comment] 2021-02-16 14:13
Hi. We are experiencing the same web page redirection issue on a native app.

1. Version of Mobile SDK Used: 8.3.0
2. Native App
3. OS Version: 14.*
4. Steps to reproduce:
It is hard to reproduce because it does not always occur.
-Leave the program for a while (a day or two), the web version of the SF page may appear.
-Enter credentials
-Webview does not display "Allow screen" and go to the SF web page

bootconfig looks similar to the attached above.

@wmathurin Could you please assist and raise the issue again for native apps as well?

I assume that SFOAuthCoordinator does not handle some specific case in decidePolicyForNavigationAction
<img width="1217" alt="navigation_decision_policy" src="https://user-images.githubusercontent.com/25912107/108074358-c4c82b00-7071-11eb-963b-acb6ca02a667.png">

**Comment by az-oolloow** [comment] 2021-02-23 04:17
@iowlit we got the EXACT same behaviour and always advise our users to kill the app and start again, which is pretty frustrating.
