### ISSUE TITLE
iOS9 Logged in user is not remembered

### ISSUE THREAD

**Issue by cgreening** [forcedotcom/SalesforceMobileSDK-iOS#1171] opened 2015-09-03 11:56 UTC
Seeing some funny behaviour on iOS9 with the logged in user not being remembered.

Expected:
Login successfully
Kill App
Start App
Auto Logged In

Actual:
Login successfully
Kill App
Start App
Asked to login again.

**Comment by jeffreyjackson** [comment] 2015-09-03 12:26
Im seeing this same issue.

**Comment by toddhalfpenny** [comment] 2015-09-03 12:32
+1 (though I'm using the Cordova plugin)

Looks like this might have (meant to have) fixed it https://github.com/wmathurin/SalesforceMobileSDK-iOS/commit/a166b555f80bb606dd05f92b93268258bd3e51d8

I have created a G+ discussion for this also https://plus.google.com/116610837536325321416/posts/co8SftDPwDM

**Comment by wmathurin** [comment] 2015-09-03 13:52
The fix has been in the unstable branch for a while, and was brought to master yesterday.
However, we have not cut a patch yet or uploaded a new version of the forceios package to npm or updated the binaries in the cordova plugin repo. We plan to do that pretty soon once we are fairly confident we have fixed all iOS9 related issues.
If you consume the SDK through cocoapods, edit your podfile to get the latest from master instead of the 3.3 version. Otherwise, you will need to recompile the binaries (*) or wait for the patch.

(*) Clone the repo (master branch), go the build repo and run ant. Then pick up the new SalesforceSDKCore.a from the artifacts repo.

**Comment by wmathurin** [comment] 2015-09-03 14:01
For the cordova plugin, there is a script in the tools directory called update.sh.

You need to fork the cordova plugin.
Clone it locally, run ./tools/update.sh -b master.
It will clone the iOS and Android repos, build what needs to be built etc.
Check everything back to your fork.

In your hybrid app, cordova plugin remove https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin, 
Then cordova plugin add https://github.com/YOUR_FORK/SalesforceMobileSDK-CordovaPlugin

Let me know if you run into any issues.

**Comment by jeffreyjackson** [comment] 2015-09-03 14:05
are you bring the "patch" as a new pod version, or is it being delivered as what is latest on master?

**Comment by toddhalfpenny** [comment] 2015-09-03 14:07
Thanks for the info re the cordova plugin @wmathurin... I shall attempt this and let you know how I get on.

**Comment by toddhalfpenny** [comment] 2015-09-03 14:59
@wmathurin et al. I have run the commands above to pull these changes into a hybrid project using the CordovaPlugin. I can confirm that the issue appears to be fixed (from my limited testing). Many thanks.

**Comment by cgreening** [comment] 2015-09-03 16:01
Can confirm that master seems to work as well.

**Comment by jeffreyjackson** [comment] 2015-09-03 16:19
did you get master to work without all of the SSL errors and removing the NSTransport dictionary key in Info.plist?

**Comment by cgreening** [comment] 2015-09-03 16:24
No, you still need this in your plist file:

```xml
<key>NSAllowsArbitraryLoads</key>
<true/>
```

**Comment by wmathurin** [comment] 2015-09-03 20:27
@cgreening Have you tried with settings like https://github.com/wmathurin/SalesforceMobileSDK-iOS/commit/6f9597a84f9e8b2564deba88479be1131148ac24 ?

**Comment by wmathurin** [comment] 2015-09-08 17:47
FYI, The 3.3.1 patch with the iOS9 fixes is now out.
https://github.com/forcedotcom/SalesforceMobileSDK-iOS/tree/v3.3.1 https://www.npmjs.com/~bhariharan

Let us know if you are still having issues.

**Closed by wmathurin** 2015-09-08 17:47 UTC
