### ISSUE TITLE
Passing custom parameters to login page

### ISSUE THREAD

**Issue by denysvarchenko** [forcedotcom/SalesforceMobileSDK-iOS#3205] opened 2020-05-22 08:56 UTC
Hello,
I need to pass additional parameters to the login page. I have found generateApprovalUrlString in the SFOAuthCoordinator class where I could probably inject my parameters, but there is too much to override and copy-paste. Is there any legal way to add additional parameters?

**Comment by bhariharan** [comment] 2020-05-22 17:02
Not at the moment. What parameters do you want to add?

**Comment by denysvarchenko** [comment] 2020-05-27 08:22
@bhariharan We need to pass the region, language and some other system info maybe. The default locale that is passed into web view is not always correct

**Comment by luminixinc** [comment] 2020-11-11 22:30
+1.

We would like to be able to pass the username parameter to the login page and have it pre-populate the login form.

Our use case is this: many of our users are SF admins with multiple orgs/logins, often with usernames that only slightly differ (e.g.: *admin1@example.com*, *admin1@example.com.int*, *admin1@example.com.uat*, etc

Currently, without the ability to pre-populate the login form with a chosen username, the user is forced to remember exactly which username was chosen and re-type it correctly into the login form.  Needless to say this is a quite error-prone process, in addition to being poor UX.

We would definitely welcome the ability to show the SF login page with a form pre-populated with a prior chosen username.

**Comment by bhariharan** [comment] 2020-11-11 22:32
@luminixinc This is currently not supported, since those fields are within the webview.

**Comment by luminixinc** [comment] 2020-11-11 22:48
@bhariharan : Understood that this is not *currently* supported, but when will it be?  Or... is this very issue without merit?  We look forward to hearing back about how to resolve this.  Thank you.

**Comment by bhariharan** [comment] 2020-11-11 22:52
It's not something we would support - it's by design. The login flow within the webview is a black box by design for security purposes.

**Comment by wmathurin** [comment] 2021-01-05 19:49
Closing issue since we have no plans to do the suggested enhancement.

**Closed by wmathurin** 2021-01-05 19:49 UTC
