### ISSUE TITLE
Cocoapods installation doesn't work with use_frameworks!

### ISSUE THREAD

**Issue by paweldudek** [forcedotcom/SalesforceMobileSDK-iOS#1251] opened 2015-11-20 09:24 UTC
1. Create a new, empty project
2. Add a Podfile with `pod 'SalesforceMobileSDK-iOS'` as dependency
3. Add `use_frameworks!` to Podfile to enable frameworks (which is required if you have Swift dependencies)
4. Try to compile the app. 

Result: The app does't compile - headers seem to be incorrectly configured in (at least) `.pch` file, didn't go any further. 

Expected: The app should compile just normally.

**Comment by powerje** [comment] 2015-11-20 18:24
fyi, this is a dupe of https://github.com/forcedotcom/SalesforceMobileSDK-iOS/issues/1072

**Comment by wmathurin** [comment] 2015-12-08 23:18
FYI, fixed in unstable (with that commit https://github.com/forcedotcom/SalesforceMobileSDK-iOS/commit/ebcff22c572bd4dc1fa74b94ee9839ba2f94ede8). Will be in our next release.

**Closed by wmathurin** 2015-12-08 23:18 UTC

**Comment by mgetzbw** [comment] 2015-12-10 15:15
@wmathurin verified in unstable that it's still not working

**Comment by khawkins** [comment] 2015-12-10 19:41
Can you post your Podfile?  I'm able to install and run with the following Podfile for my app:

```
use_frameworks!
pod 'SalesforceMobileSDK-iOS/SalesforceRestAPI', :git => 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git', :branch => 'unstable', :submodules => true
```
I'm using CocoaPods 0.39.0.

**Comment by khawkins** [comment] 2015-12-10 19:53
Note that with the next (unstable) release, we've added a default subspec, SalesforceSDKCore.  So if you need to use any of the satellite dependencies, like SalesforceRestAPI or SmartSync, etc., you'll need to explicitly specify that subspec in your Podfile.

**Comment by mgetzbw** [comment] 2015-12-11 13:56
@khawkins this is rather embarrassing it appears my report was in error I had forgotten to do a `pod update` when testing, apologies
